"""Actual factory, equipment and AnimateHero/companion pose branches. Managed TRS, not Unity.
python3 export.py output dotnet [--before]
"""
from pathlib import Path
import sys,subprocess,os
ROOT=Path(__file__).resolve().parents[3];out=Path(sys.argv[1]).resolve();dotnet=sys.argv[2];before='--before' in sys.argv
src=(ROOT/'ArtSource/ActorModules/export_constructions.py').read_text().split('subprocess.run(')[0]
sys.argv=['export',str(ROOT),str(out),dotnet];ns={'__file__':str(ROOT/'ArtSource/ActorModules/export_constructions.py')};exec(src,ns);p=out/'export';extract=ns['ns']['extract']
f=p/'OptionalPilotBoundary.cs';s=f.read_text();a=s.index('namespace Emberfall { internal static class ActorSilhouetteF1');s=s[:a]+s[s.index('\n',a):];f.write_text(s)
(p/'ActorSilhouetteF1.cs').write_text((ROOT/'Assets/Scripts/Combat/ActorSilhouetteF1.cs').read_text())
# Before is the exact inherited Companion factory (which has the old crown scale/wing parent).
if before:
 prior=subprocess.check_output(['git','show','0daa0f2:Assets/Scripts/Combat/CombatModel.cs'],cwd=ROOT,text=True)
 m=p/'Model.cs';s=m.read_text();s=s.replace(extract(ns['ns']['model'],'public static CombatModel Companion('),extract(prior,'public static CombatModel Companion('));m.write_text(s)
source=(ROOT/'Assets/Scripts/Combat/CombatModel.cs').read_text();motion=(ROOT/'Assets/Scripts/Combat/CombatModel.Motion.cs').read_text();comp=(ROOT/'Assets/Scripts/Combat/CombatModel.CompanionAppearance.cs').read_text()
for folder,name in [('Core','HeroMotionStyle'),('Core','LocomotionPoseState'),('Core','VisualMotionEnvelope'),('Core','BasicActionTimeline'),('Core','CasterPoseRecipe'),('Combat','CombatModel.CastPoses')]: (p/(name+'.cs')).write_text((ROOT/'Assets/Scripts'/folder/(name+'.cs')).read_text())
body='using System;using UnityEngine;namespace Emberfall{public sealed partial class CombatModel {private bool isolatedPreview,pilotAirborne;private float previewTime,actionAge,actionDuration,gaitPhase;private int actionStartedFrame;private readonly LocomotionPoseState locomotion=new LocomotionPoseState();private readonly VisualMotionEnvelope visualMotion=new VisualMotionEnvelope();private bool SampleBlenderPilot(bool a,float b,bool c){return false;}private void AdvanceVisualMotion(float dt){throw new Exception("frozen review clock");}private void ApplyVisualRecovery(float dt){}private void ApplyAuthoredVanguardPose(bool a,float b,bool c){}'
for sig in ['private static Quaternion Pose(','private void AnimateHero(','private static void AimArm(']:body+=extract(source,sig)
body+=extract(motion,'private void ApplyHeroLocomotion(')
body+='private Transform companionInsignia;private float companionPreparation,companionRecallLift;private int companionAppearanceKey=-1;'
for sig in ['public void SetCompanionAppearance(','public void SetCompanionRecall(','public void SetCompanionAttackPreparation(','private void ApplyCompanionPose(']:body+=extract(comp,sig)
# Companion motion branches are copied verbatim from Animate; no substitute pose model.
def branch(label):
 a=source.index(label,source.index('public void Animate('));a=source.index('{',a)+1;b=a;d=1
 while d:d+=(source[b]=='{')-(source[b]=='}');b+=1
 return source[a:b-1]
body+='''public void ReviewPose(int mode){Time.time=1;Time.frameCount=1;isolatedPreview=true;previewTime=1;if(isHero){actionStartedFrame=1;actionAge=mode==2?.25f:mode==3?.52f:0;actionDuration=mode>=2?1:0;actionBasic=mode==2;actionSkill=0;if(mode==1)for(int i=0;i<6;i++)locomotion.Advance(.06f,.08f,.05f,2,true,false,0);AnimateHero(locomotion.Speed,0,false,0);}else{float attack=mode==2?.5f:mode==3?.8f:0;float stride=.7f;float walk=mode==1?20:0;body.localRotation=bodyRestRotation;if(floating){'''+branch('else if (floating)')+'''}else if(treantCompanion){if(leftLeg!=null)leftLeg.localRotation=Quaternion.Euler(walk,0,-2);if(rightLeg!=null)rightLeg.localRotation=Quaternion.Euler(-walk,0,2);if(leftArm!=null)leftArm.localRotation=Quaternion.Euler(-walk*.6f,0,-8);'''+branch('else if (treantCompanion)')+'''}SetCompanionAttackPreparation(mode==2?.5f:0);SetCompanionRecall(mode==3?.5f:0);ApplyCompanionPose();}}}}'''
(p/'Motion.cs').write_text(body)
f=p/'Fixture.cs';s=f.read_text().replace('public static float deltaTime=.016f,time;','public static float deltaTime=.016f,time;public static int frameCount;').replace('public Quaternion rotation=>parent==null?localRotation:parent.rotation*localRotation;','public Quaternion rotation{get=>parent==null?localRotation:parent.rotation*localRotation;set=>localRotation=parent==null?value:Quaternion.Inverse(parent.rotation)*value;}public void Rotate(float x,float y,float z,Space s){localRotation=localRotation*Quaternion.Euler(x,y,z);}')
s=s.replace('public struct Vector3 {','public enum Space{Self,World}public struct Vector3 {public static Vector3 Lerp(Vector3 a,Vector3 b,float t)=>a+(b-a)*Mathf.Clamp01(t);public static Vector3 ProjectOnPlane(Vector3 v,Vector3 n)=>v-n*(v.x*n.x+v.y*n.y+v.z*n.z);')
s=s.replace('public struct Quaternion {','public struct Quaternion {public static Quaternion Euler(Vector3 v)=>Euler(v.x,v.y,v.z);public static Quaternion Slerp(Quaternion a,Quaternion b,float t)=>new Quaternion{q=System.Numerics.Quaternion.Slerp(a.q,b.q,t)};public static Quaternion FromToRotation(Vector3 a,Vector3 b){a=a.normalized;b=b.normalized;float d=a.x*b.x+a.y*b.y+a.z*b.z;if(d<-.9999f)return Euler(180,0,0);var c=Vector3.Cross(a,b);return new Quaternion{q=System.Numerics.Quaternion.Normalize(new System.Numerics.Quaternion(c.x,c.y,c.z,1+d))};}')
s=s.replace('public static class Mathf{','public static class Mathf{public static float Sqrt(float x)=>(float)Math.Sqrt(x);public static float Max(float a,float b)=>Math.Max(a,b);public static float Min(float a,float b)=>Math.Min(a,b);public static float Pow(float a,float b)=>(float)Math.Pow(a,b);public static float SmoothStep(float a,float b,float t){t=Clamp01(t);return a+(b-a)*t*t*(3-2*t);}')
# Palette comes from actual GameBalance, not the legacy geometry fixture's placeholder colors.
gametypes=(ROOT/'Assets/Scripts/Core/GameTypes.cs').read_text()
old=s[s.index('public static class GameBalance'):];old=extract(old,'public static class GameBalance')
real='public static class GameBalance {'+extract(gametypes,'public static readonly Color[] ClassColors')+';'+extract(gametypes,'public static Color ClassColor(')+extract(gametypes,'public static Color RarityColor(')+'}'
s=s.replace(old,real)
f.write_text(s)
(p/'Exporter.cs').write_text(r'''using System;using System.Linq;using System.Collections.Generic;using System.Text.Json;using Emberfall;using UnityEngine;
class Exporter{static void Check(bool ok,string why){if(!ok)throw new Exception(why);}static object Geo(CombatModel m)=>m.GetComponentsInChildren<MeshFilter>(false).Where(x=>x.sharedMesh?.vertices!=null&&x.GetComponent<Renderer>().enabled).Select(x=>new{name=x.transform.name,mesh=x.sharedMesh.name,color=new[]{x.GetComponent<Renderer>().sharedMaterial.color.r,x.GetComponent<Renderer>().sharedMaterial.color.g,x.GetComponent<Renderer>().sharedMaterial.color.b},vertices=x.sharedMesh.vertices.Select(v=>{var w=x.transform.TransformPoint(v);return new[]{w.x,w.y,w.z};}).ToArray(),triangles=x.sharedMesh.triangles}).ToArray();
static void Main(){ActorSilhouetteF1.Enabled=ENABLED;var cases=new List<object>();for(int hero=1;hero<4;hero++)foreach(int tier in new[]{-1,0,4}){var host=new GameObject("hero");var m=CombatModel.Hero(host.transform,(HeroClass)hero);if(tier>=0)m.ApplyEquipment(new ItemData{id="w",slot=ItemSlot.Weapon,level=tier==0?1:100,rarity=Rarity.Legendary},new ItemData{id="a",slot=ItemSlot.Armor,level=tier==0?1:100,rarity=Rarity.Legendary},null);UnityEngine.Object.Flush();var meshes=m.GetComponentsInChildren<MeshFilter>(false).Select(x=>x.sharedMesh).ToArray();for(int pose=0;pose<4;pose++){m.ReviewPose(pose);Check(m.GetComponentsInChildren<MeshFilter>(true).Count(x=>meshes.Contains(x.sharedMesh))>=meshes.Length,"hero pose preserves all body resources");cases.Add(new{name=((HeroClass)hero).ToString(),tier=tier,pose=pose,parts=Geo(m)});}UnityEngine.Object.Destroy(host);UnityEngine.Object.Flush();}
for(int form=1;form<=2;form++){var host=new GameObject("companion");var m=CombatModel.Companion(host.transform,(SummonedCompanion.Kind)form);m.SetCompanionAppearance((SummonedCompanion.Kind)form,3,true);UnityEngine.Object.Flush();if(form==1&&ActorSilhouetteF1.Enabled)Check(m.GetComponentsInChildren<Transform>(true).Where(x=>x.name=="Spirit wing").All(x=>x.parent.name=="Companion rigid body attachments"),"spirit wings follow rigid pose without inheriting soft core scale");var before=m.GetComponentsInChildren<MeshFilter>(false).Select(x=>x.sharedMesh).ToArray();for(int pose=0;pose<4;pose++){m.ReviewPose(pose);Check(m.GetComponentsInChildren<MeshFilter>(false).Select(x=>x.sharedMesh).SequenceEqual(before),"companion pose preserves same body meshes");cases.Add(new{name=((SummonedCompanion.Kind)form).ToString(),tier=3,pose=pose,parts=Geo(m)});}UnityEngine.Object.Destroy(host);UnityEngine.Object.Flush();}
System.IO.File.WriteAllText(@"OUTPUT",JsonSerializer.Serialize(cases));Console.WriteLine("PASS actual F1 factories + equipment + AnimateHero/AimArm/caster/companion pose branches; 44 combinations, same-body mesh identity throughout");}}'''.replace('OUTPUT',str(out/'actors.json')).replace('ENABLED','false' if before else 'true'))
subprocess.run([dotnet,'run','--project',str(p/'Export.csproj')],env=dict(os.environ,DOTNET_CLI_HOME=str(out/'cli')),check=True)
