using System;using System.Linq;using System.Reflection;using System.Text;using System.Runtime.CompilerServices;using Emberfall;using UnityEngine;
class ArrowBatchGenerationProductionTests
{
 static int checks;static readonly BindingFlags I=BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic,S=BindingFlags.Static|BindingFlags.NonPublic;
 static void Check(bool b,string m){checks++;if(!b)throw new Exception(m);}
 static object Field(object o,string name)=>o.GetType().GetField(name,I).GetValue(o);
 static FilledSkillVfx Effect(FilledSkillVfx.ArrowBatchHandle h)=>(FilledSkillVfx)Field(h,"effect");
 static void Reset(){typeof(FilledSkillVfx).GetMethod("ResetAssets",S).Invoke(null,null);foreach(var o in GameObject.All.ToArray())UnityEngine.Object.Destroy(o);GameObject.All.Clear();typeof(CombatVisualLease).GetMethod("Reset",S).Invoke(null,null);Application.isMobilePlatform=true;EffectPreferences.ReducedEffects=true;CombatSight.Wall=float.PositiveInfinity;Time.deltaTime=.01f;}
 static PlayerController Hero(){var h=new GameObject("hero").AddComponent<PlayerController>();GameSession.Instance=new GameSession{Player=h,HasStarted=true};return h;}
 static string Id(object o)=>o==null?"null":RuntimeHelpers.GetHashCode(o).ToString();
 static string V(object o){if(o==null)return "null";if(o is Vector3 v)return $"{v.x:R},{v.y:R},{v.z:R}";if(o is Vector2 u)return $"{u.x:R},{u.y:R}";if(o is Quaternion q)return V(q*Vector3.right)+"/"+V(q*Vector3.up)+"/"+V(q*Vector3.forward);if(o is Color c)return $"{c.r:R},{c.g:R},{c.b:R},{c.a:R}";return o.GetType().IsValueType||o is string?o.ToString():Id(o);}
 static void Fields(StringBuilder b,object o){foreach(var f in o.GetType().GetFields(I).OrderBy(f=>f.Name))b.Append(f.Name).Append('=').Append(V(f.GetValue(o))).Append(';');}
 static void MeshState(StringBuilder b,Mesh m){b.Append("mesh=").Append(Id(m));if(m==null)return;b.Append(m.Destroyed).Append(m.name);foreach(var v in m.vertices)b.Append(V(v));foreach(var v in m.uv)b.Append(V(v));if(m.normals!=null)foreach(var v in m.normals)b.Append(V(v));foreach(var t in m.triangles)b.Append(t).Append(',');}
 static void TransformState(StringBuilder b,Transform t){b.Append("parent=").Append(Id(t.parent)).Append("go=").Append(t.gameObject.name).Append(t.gameObject.activeSelf).Append(t.gameObject.Destroyed).Append(V(t.localPosition)).Append(V(t.localScale)).Append(V(t.localRotation));}
 static string Snapshot(FilledSkillVfx fx){var b=new StringBuilder();Fields(b,fx);TransformState(b,fx.transform);Fields(b,Field(fx,"block"));var lease=fx.GetComponent<CombatVisualLease>();Fields(b,lease);var ticket=Field(lease,"ticket");if(ticket!=null)Fields(b,ticket);foreach(var part in (Array)Field(fx,"pieces")){if(part==null){b.Append("nullpiece");continue;}Fields(b,part);var t=(Transform)Field(part,"Transform");if(t!=null){TransformState(b,t);var renderer=t.gameObject.GetComponent<MeshRenderer>();Fields(b,renderer);MeshState(b,t.gameObject.GetComponent<MeshFilter>().sharedMesh);}MeshState(b,(Mesh)Field(part,"OwnedMesh"));}foreach(var member in (System.Collections.IEnumerable)typeof(FilledSkillVfx).GetField("finales",S).GetValue(null))b.Append("finale=").Append(Id(member));b.Append("leaseActive=").Append(CombatVisualLease.Active).Append("fxActive=").Append(typeof(FilledSkillVfx).GetField("active",S).GetValue(null));return b.ToString();}
 static void Evict(FilledSkillVfx old,PlayerController hero){for(int n=0;n<11;n++)FilledSkillVfx.Impact(hero,Vector3.zero,1,FilledVfxKind.Fire,new Color(1,0,0),CombatVisualPriority.Finale,n+100);Check(CombatVisualLease.Active==12,"real lease pool filled");FilledSkillVfx.Impact(hero,Vector3.zero,1,FilledVfxKind.Fire,new Color(1,0,0),CombatVisualPriority.Finale,999);Check(!old.gameObject.activeSelf&&Field(old,"owner")==null,"real priority eviction retires old sequence batch");}
 static void Main(string[] args){Resources.Root=args[0];
 foreach(string context in new[]{"same-owner-same-cast","cross-owner","cross-room","cross-session"})foreach(bool arrow in new[]{true,false}){
  Reset();var h=Hero();var oldGame=GameSession.Instance;var seq=new GameObject("old sequence").AddComponent<SequenceProbe>();seq.Setup(h,77);var oldHandle=seq.Handle;var oldFx=Effect(oldHandle);Check(oldHandle.IsValid,"sequence Configure gets live handle");ulong oldGen=(ulong)Field(oldFx,"rentGeneration");var oldCallback=(Action)Field(oldFx.GetComponent<CombatVisualLease>(),"retireAction");Evict(oldFx,h);Check(!oldHandle.IsValid,"lease eviction invalidates old handle");
  var newHero=h;if(context=="cross-owner")newHero=Hero();else if(context=="cross-room")h.CombatEpoch++;else if(context=="cross-session")GameSession.Instance=new GameSession{Player=h,HasStarted=true};
  FilledSkillVfx.ArrowBatchHandle current=default;FilledSkillVfx currentFx;
  if(arrow){current=FilledSkillVfx.BeginArrowBatch(newHero,new Vector3(2,0,3),2,new Color(.2f,.8f,.4f,.7f),true,CombatVisualPriority.Finale,77);current.ArrowBeat(new Vector3(2,0,3),2,true);currentFx=Effect(current);}
  else{FilledSkillVfx.Impact(newHero,new Vector3(2,0,3),2,FilledVfxKind.Fire,new Color(.2f,.8f,.4f,.7f),CombatVisualPriority.Finale,77);currentFx=oldFx;}
  Check(ReferenceEquals(oldFx,currentFx)&&currentFx.gameObject.activeInHierarchy,"actual same component re-rented to new cast");Check((ulong)Field(currentFx,"rentGeneration")>oldGen,"every rental advances generation even same owner/cast id");Check((int)Field(currentFx,"finaleCast")==77,"regression includes reused same cast id");
  // Do not rely on owner/cast/epoch checks: same-owner-same-cast matches all of them.
  string before=Snapshot(currentFx);oldCallback();Check(Snapshot(currentFx)==before,"stale lease callback cannot mutate new rental snapshot");int oldHits=h.Hits;seq.gameObject.Call("Update");Check(Snapshot(currentFx)==before,"stale sequence Update cannot mutate new rental snapshot");if(context!="cross-room")Check(h.Hits==oldHits+1,"old sequence retains actual scheduled gameplay beat");
  seq.gameObject.Call("OnDisable");Check(Snapshot(currentFx)==before,"stale sequence OnDisable cannot retire new rental snapshot");
  oldHandle.ArrowBeat(new Vector3(19,0,17),7,true);oldHandle.Retire();oldHandle.Dispose();Check(Snapshot(currentFx)==before,"stale direct ArrowBeat Retire Dispose are no-ops");
  if(arrow){Check(current.IsValid,"current handle stays valid");current.Dispose();Check(!current.IsValid&&!currentFx.gameObject.activeSelf,"current Dispose retires own rental");}else currentFx.Retire();
 }
 // Each valid handle retires normally, and old references remain invalid after reset/re-rent.
 foreach(string exit in new[]{"Retire","Dispose","room","session"}){Reset();var h=Hero();var a=FilledSkillVfx.BeginArrowBatch(h,Vector3.zero,2,new Color(1,1,1),castId:5);var fx=Effect(a);Check(a.IsValid,"normal handle valid");if(exit=="Retire")a.Retire();else if(exit=="Dispose")a.Dispose();else{if(exit=="room")h.CombatEpoch++;else GameSession.Instance=new GameSession{Player=h,HasStarted=true};Check(!a.IsValid,"room/session invalidates handle");string before=Snapshot(fx);a.ArrowBeat(Vector3.one,3,true);a.Dispose();Check(Snapshot(fx)==before,"invalid-context handle cannot mutate rental");fx.gameObject.Call("Update");}Check(!a.IsValid&&!fx.gameObject.activeSelf&&CombatVisualLease.Active==0,"normal lifecycle cleanup remains complete");}
 Reset();Console.WriteLine("PASS "+checks+" real persistent sequence/lease-eviction/re-rent generation assertions with full new-rental state snapshots; managed, not Unity.");}
}
