using System;using System.Linq;using System.Collections.Generic;using System.Reflection;using UnityEngine;using Emberfall;
namespace UnityEngine{
 public enum RuntimeInitializeLoadType{SubsystemRegistration}public class RuntimeInitializeOnLoadMethodAttribute:Attribute{public RuntimeInitializeOnLoadMethodAttribute(RuntimeInitializeLoadType x){}}
 public class Object{public string name;public bool destroyed;public static GameObject Instantiate(GameObject x,Transform p,bool w)=>x.Clone(p);public static void Destroy(Object x){if(x==null)return;x.destroyed=true;if(x is GameObject g){g.SetActive(false);foreach(var c in g.Components.ToArray())c.GetType().GetMethod("OnDestroy",BindingFlags.Instance|BindingFlags.NonPublic)?.Invoke(c,null);foreach(var t in g.transform.Children.ToArray())Destroy(t.gameObject);}}}
 public class Component:Object{public GameObject gameObject;public Transform transform=>gameObject.transform;public T[] GetComponentsInChildren<T>(bool inactive)where T:Component=>gameObject.GetComponentsInChildren<T>(inactive);public T GetComponent<T>()where T:Component=>gameObject.Components.OfType<T>().FirstOrDefault();}
 public class MonoBehaviour:Component{}
 public class Transform:Component{public Vector3 localPosition,localScale=Vector3.one;public Quaternion localRotation=Quaternion.identity;public Transform parent;public List<Transform> Children=new List<Transform>();public Quaternion rotation{get=>parent==null?localRotation:parent.rotation*localRotation;set=>localRotation=parent==null?value:Quaternion.Inverse(parent.rotation)*value;}public Vector3 TransformDirection(Vector3 v)=>rotation*v;public Vector3 InverseTransformDirection(Vector3 v)=>Quaternion.Inverse(rotation)*v;public Vector3 position{get=>parent==null?localPosition:parent.TransformPoint(localPosition);set=>localPosition=value;}public System.Collections.Generic.IEnumerator<Transform> GetEnumerator()=>Children.GetEnumerator();public void SetParent(Transform p){parent?.Children.Remove(this);parent=p;p?.Children.Add(this);}public bool IsChildOf(Transform p)=>this==p||(parent!=null&&parent.IsChildOf(p));public Vector3 TransformPoint(Vector3 p){var local=localPosition+localRotation*Vector3.Scale(localScale,p);return parent==null?local:parent.TransformPoint(local);}}

 public class GameObject:Object{public static readonly List<GameObject> All=new List<GameObject>();public readonly List<Component> Components=new List<Component>();public Transform transform;public bool activeSelf=true;public bool activeInHierarchy=>activeSelf&&(transform.parent==null||transform.parent.gameObject.activeInHierarchy);public GameObject(string n=""){All.Add(this);name=n;transform=AddComponent<Transform>();transform.name=n;}public void SetActive(bool a){activeSelf=a;}public T AddComponent<T>()where T:Component,new(){var c=new T{gameObject=this};Components.Add(c);return c;}public T[] GetComponentsInChildren<T>(bool inactive)where T:Component=>Components.OfType<T>().Concat(transform.Children.SelectMany(t=>t.gameObject.GetComponentsInChildren<T>(inactive))).ToArray();public GameObject Clone(Transform p){var g=new GameObject(name);g.transform.SetParent(p);g.transform.localPosition=transform.localPosition;g.transform.localScale=transform.localScale;g.transform.localRotation=transform.localRotation;g.activeSelf=activeSelf;foreach(var c in Components){if(c is Renderer r){var v=g.AddComponent<Renderer>();v.enabled=r.enabled;v.sharedMaterial=r.sharedMaterial;}if(c is MeshFilter m)g.AddComponent<MeshFilter>().sharedMesh=m.sharedMesh;if(c is Animator a){var v=g.AddComponent<Animator>();v.enabled=a.enabled;v.applyRootMotion=a.applyRootMotion;}if(c is Animation a2){var v=g.AddComponent<Animation>();v.enabled=a2.enabled;v.playAutomatically=a2.playAutomatically;}}foreach(var t in transform.Children)t.gameObject.Clone(g.transform);return g;}}
 public class Renderer:Component{public bool enabled=true;public Material sharedMaterial;}public class Shader:Object{public bool isSupported=true;}public class Texture:Object{}public class Texture2D:Texture{public int width=1024,height=1024;}public class SkinnedMeshRenderer:Renderer{public Mesh sharedMesh;}public class Material:Object{public Shader shader=new Shader{name="Standard"};public bool Keyword=true,Properties=true;public Dictionary<string,Texture> Textures=new Dictionary<string,Texture>{{"_MainTex",new Texture2D()},{"_MetallicGlossMap",new Texture2D()}};public bool HasProperty(string n)=>Properties;public bool IsKeywordEnabled(string n)=>Keyword;public Texture GetTexture(string n)=>Textures.TryGetValue(n,out var t)?t:null;}public class LineRenderer:Component{public void SetPosition(int i,Vector3 p){}}public class Mesh:Object{}public class MeshFilter:Component{public Mesh sharedMesh;}public class Animator:Component{public bool enabled=true,applyRootMotion=true;}public class Animation:Component{public bool enabled=true,playAutomatically=true;}
 public class AnimationClip:Object{public float length=2;public bool empty,Bound=true,ThrowOnSample;public static AnimationClip Last;public static float At;public static int Samples;public void SampleAnimation(GameObject g,float t){if(ThrowOnSample)throw new InvalidOperationException("bad imported binding");Last=this;At=t;Samples++;if(Bound)LayerFixture.ApplyClip(g,name,t/length);}}

 public static class Resources{public static Dictionary<string,Object> Items=new Dictionary<string,Object>();public static AnimationClip[] Clips=new AnimationClip[0];public static int Loads;public static T Load<T>(string n)where T:Object{Loads++;return Items.TryGetValue(n,out var v)?v as T:null;}public static T[] LoadAll<T>(string n)where T:Object=>Clips.OfType<T>().ToArray();}
 public struct Vector3{public float x,y,z;public Vector3(float a,float b,float c){x=a;y=b;z=c;}public static bool operator ==(Vector3 a,Vector3 b)=>a.x==b.x&&a.y==b.y&&a.z==b.z;public static bool operator !=(Vector3 a,Vector3 b)=>!(a==b);public override bool Equals(object o)=>o is Vector3 v&&this==v;public override int GetHashCode()=>x.GetHashCode();public float sqrMagnitude=>x*x+y*y+z*z;public float magnitude=>(float)Math.Sqrt(sqrMagnitude);public Vector3 normalized=>magnitude>0?this*(1/magnitude):zero;public static Vector3 Lerp(Vector3 a,Vector3 b,float t)=>a*(1-t)+b*t;public static Vector3 Scale(Vector3 a,Vector3 b)=>new Vector3(a.x*b.x,a.y*b.y,a.z*b.z);public static Vector3 zero=>new Vector3();public static Vector3 one=>new Vector3(1,1,1);public static Vector3 operator +(Vector3 a,Vector3 b)=>new Vector3(a.x+b.x,a.y+b.y,a.z+b.z);public static Vector3 up=>new Vector3(0,1,0);public static Vector3 operator *(Vector3 a,float b)=>new Vector3(a.x*b,a.y*b,a.z*b);}
 public struct Color{public Color(float a,float b,float c){}}public struct Quaternion{internal System.Numerics.Quaternion q;public static bool operator ==(Quaternion a,Quaternion b)=>a.q==b.q;public static bool operator !=(Quaternion a,Quaternion b)=>!(a==b);public override bool Equals(object o)=>o is Quaternion v&&this==v;public override int GetHashCode()=>q.GetHashCode();public static Quaternion Inverse(Quaternion a)=>new Quaternion{q=System.Numerics.Quaternion.Inverse(a.q)};public static Quaternion operator *(Quaternion a,Quaternion b)=>new Quaternion{q=a.q*b.q};public static Quaternion identity=>new Quaternion{q=System.Numerics.Quaternion.Identity};public static Quaternion Euler(float x,float y,float z)=>new Quaternion{q=System.Numerics.Quaternion.CreateFromAxisAngle(System.Numerics.Vector3.UnitY,y*(float)Math.PI/180)*System.Numerics.Quaternion.CreateFromAxisAngle(System.Numerics.Vector3.UnitX,x*(float)Math.PI/180)*System.Numerics.Quaternion.CreateFromAxisAngle(System.Numerics.Vector3.UnitZ,z*(float)Math.PI/180)};public static Quaternion Slerp(Quaternion a,Quaternion b,float t)=>new Quaternion{q=System.Numerics.Quaternion.Slerp(a.q,b.q,t)};public static Vector3 operator *(Quaternion a,Vector3 b){var v=System.Numerics.Vector3.Transform(new System.Numerics.Vector3(b.x,b.y,b.z),a.q);return new Vector3(v.X,v.Y,v.Z);}}public static class Time{public static float time,deltaTime;public static int frameCount;}public static class Mathf{public static float Clamp01(float x)=>Clamp(x,0,1);public static float SmoothStep(float a,float b,float t){t=Clamp01(t);return a+(b-a)*t*t*(3-2*t);}public static float Clamp(float a,float b,float c)=>Math.Max(b,Math.Min(c,a));public static float Max(float a,float b)=>Math.Max(a,b);public static int CeilToInt(float a)=>(int)Math.Ceiling(a);public static float Abs(float x)=>Math.Abs(x);public static float Min(float a,float b)=>Math.Min(a,b);}
}
namespace Emberfall{
 public enum HeroClass{Vanguard,Arcanist,Ranger,Summoner}
 public sealed partial class CombatModel:MonoBehaviour{
 public HeroClass heroClass;public bool isHero=true,isolatedPreview,actionBasic,dying;public float previewTime,actionDuration,actionAge,recoveryAge=1,smoothedSpeed,gaitPhase;public int actionSkill,actionStartedFrame,weaponActionId,swingCount;public Transform spine,swordRig,staffRig,bowRig,arrowRig;public float phase;public FakeCloth tailoredCloth;public class FakeCloth{public void SetMotion(float a,float b){}}
 public Motion locomotion=new Motion();public class Motion{public float Landing,Side,Forward,Phase,Speed;}
 private Dictionary<string,Material> palette=new Dictionary<string,Material>();private void BeginVisualRecovery(bool ignored=true){}private void AdvanceVisualMotion(float dt){}
 public void Init(){spine=transform;ConfigureBlenderPilot();RecordPilotWalking(Vector3.zero,.02f,6,true,false);}public bool Sample(bool acting=false,float progress=0,bool hurt=false)=>SampleBlenderPilot(acting,progress,hurt);
 public void Tick(float dt,bool hurt=false)=>AnimateHero(locomotion.Speed,1,hurt,dt);
 public BlenderPilotVisual View=>blenderPilot;public bool Visible=>pilotVisible;
 public void Unsupported(string which){pilotHasGear=which=="gear";pilotHasFashion=which=="fashion";pilotAirborne=which=="airborne";pilotCharging=which=="charge";dying=which=="death";locomotion.Landing=which=="landing"?1:0;locomotion.Side=which=="strafe"?1:0;locomotion.Forward=which=="backwards"?-1:0;}
 }
}
class BlenderPilotAdapterProductionTests{
 static int n;static void C(bool b,string m){n++;if(!b)throw new Exception(m);}static GameObject Child(GameObject root,string name){var g=new GameObject(name);g.transform.SetParent(root.transform);return g;}
 static GameObject Asset(string omit=null){var g=new GameObject("Vanguard");g.AddComponent<Animator>();var inactive=Child(g,"inactive animation");inactive.SetActive(false);inactive.AddComponent<Animation>();g.AddComponent<Renderer>().sharedMaterial=new Material();g.AddComponent<MeshFilter>().sharedMesh=new Mesh();LayerFixture.Build(g,omit);return g;}
 static void Ready(string omit=null){Resources.Items.Clear();Resources.Items["BlenderPilot/Vanguard"]=Asset(omit);Resources.Items["BlenderPilot/Pilot_Atlas_Standard"]=new Material();Resources.Clips=new[]{"Pilot_Idle","Pilot_Move","Pilot_Basic","Pilot_Hit","Pilot_Skill"}.Select(x=>new AnimationClip{name=x,length=2}).ToArray();}
 static CombatModel Model(){var root=new GameObject("model");var model=root.AddComponent<CombatModel>();model.heroClass=HeroClass.Vanguard;Child(root,"visible old").AddComponent<Renderer>().enabled=true;Child(root,"hidden old").AddComponent<Renderer>().enabled=false;model.swordRig=Child(root,"procedural sword").transform;model.swordRig.localPosition=new Vector3(-10,0,0);model.Init();return model;}
 static void Main(){
 C(!BlenderPilotArt.Enabled,"pilot disabled on fresh startup");Ready();int loads=Resources.Loads;C(BlenderPilotVisual.Create(null)==null&&Resources.Loads==loads,"disabled pilot never loads assets");
 BlenderPilotArt.Enabled=true;Resources.Items.Clear();C(BlenderPilotVisual.Create(null)==null,"missing model falls back");
 foreach(var socket in new[]{"Anchor_Pommel","Anchor_Grip","Anchor_Guard","Anchor_BladeRoot","Anchor_Tip"}){Ready(socket);C(BlenderPilotVisual.Create(null)==null,"each missing socket falls back");C(!GameObject.All.Any(g=>g.name=="Blender pilot visual (sampled skeleton)"&&!g.destroyed),"missing socket destroys incomplete imported instance");}
 foreach(var clip in new[]{"Pilot_Idle","Pilot_Move","Pilot_Basic","Pilot_Hit","Pilot_Skill"}){Ready();Resources.Clips=Resources.Clips.Where(x=>x.name!=clip).ToArray();C(BlenderPilotVisual.Create(null)==null,"each missing clip falls back");C(!GameObject.All.Any(g=>g.name=="Blender pilot visual (sampled skeleton)"&&!g.destroyed),"missing clip destroys incomplete imported instance");}
 BlenderPilotArt.Enabled=true;typeof(BlenderPilotArt).GetMethod("ResetForPlayerStartup",BindingFlags.Static|BindingFlags.NonPublic).Invoke(null,null);C(!BlenderPilotArt.Enabled,"subsystem startup resets stale opt-in without domain reload");BlenderPilotArt.Enabled=true;Ready();var m=Model();C(m.View!=null&&m.View.Ready,"complete imported asset configures");C(!m.View.gameObject.activeSelf,"imported root stays hidden until first sample");C(m.View.GetComponentsInChildren<Animator>(true).All(a=>!a.enabled&&!a.applyRootMotion)&&m.View.GetComponentsInChildren<Animation>(true).All(a=>!a.enabled&&!a.playAutomatically),"manual sampler disables all automatic drivers including inactive descendants");
 var old=m.GetComponentsInChildren<Renderer>(true).Where(x=>!x.transform.IsChildOf(m.View.transform)).ToArray();C(m.Sample()&&old.All(x=>!x.enabled),"supported pilot hides procedural renderers");
 for(int swing=0;swing<4;swing++){m.swingCount=swing;C(m.WeaponSwingSide==-1,"authored external sword keeps fixed sampled swing side");}
 foreach(float interval in new[]{.18f,.46f,.9f}){Time.frameCount++;int before=AnimationClip.Samples;m.PlayAction(-1,true,interval);C(AnimationClip.Samples==before+3&&AnimationClip.Last.name=="Pilot_Basic"&&Math.Abs(AnimationClip.At/AnimationClip.Last.length-.52f)<.0001f,"actual PlayAction commit samples contact .52 without hidden windup");C(m.TryGetWeaponVisualAnchor(WeaponVisualAnchor.SwordTip,out var anchor)&&LayerFixture.Near(anchor,m.View.GetComponentsInChildren<Transform>(true).Single(x=>x.name=="Anchor_Tip").position),"ribbon anchor reads the sampled external tip");}
 m.PlayAction(7,false);C(AnimationClip.Last.name=="Pilot_Skill","representative skill commit selects imported skill clip");m.locomotion.Speed=1;m.locomotion.Phase=(float)Math.PI;m.Sample();C(AnimationClip.Last.name=="Pilot_Move"&&Math.Abs(AnimationClip.At-1)<.0001f,"movement bridge samples phase through actual imported clip length");m.locomotion.Speed=0;Time.time=2;m.Sample(false,0,true);C(AnimationClip.Last.name=="Pilot_Hit","hurt edge selects imported hit clip");Time.time=2.3f;m.Sample(false,0,false);C(LayerFixture.MatchesClip(m.View.gameObject,"Pilot_Idle",.15f),"hurt clip expires into idle");
 foreach(string reason in new[]{"gear","fashion","airborne","charge","death","landing","strafe","backwards","skill"}){m.Unsupported(reason);m.actionBasic=false;m.actionSkill=reason=="skill"?2:7;C(!m.Sample(reason=="skill",.52f),"unsupported states use procedural fallback");C(!m.View.gameObject.activeSelf&&old[0].enabled&&!old[1].enabled,"fallback restores each original renderer enabled state");C(m.TryGetWeaponVisualAnchor(WeaponVisualAnchor.SwordTip,out var a)&&a.x==-10,"hidden pilot does not supply sword anchors");m.Unsupported("");C(m.Sample(),"supported state re-enters pilot");}
 BlenderPilotArt.Enabled=false;C(!m.Sample()&&old[0].enabled&&!old[1].enabled,"runtime opt-out restores originals");for(int swing=0;swing<4;swing++){m.swingCount=swing;C(m.WeaponSwingSide==(swing%2==0?1:-1),"procedural fallback preserves alternating swing side");}BlenderPilotArt.Enabled=true;m.Sample();
 var mesh=m.View.GetComponentsInChildren<MeshFilter>(true)[0].sharedMesh;var material=m.View.GetComponentsInChildren<Renderer>(true)[0].sharedMaterial;C(object.ReferenceEquals(mesh,Resources.Load<GameObject>("BlenderPilot/Vanguard").GetComponentsInChildren<MeshFilter>(true)[0].sharedMesh),"imported mesh remains shared");UnityEngine.Object.Destroy(m.gameObject);C(!mesh.destroyed&&!material.destroyed,"destroying model never owns or destroys imported shared assets");
 Ready();var preview=Model();preview.isolatedPreview=true;preview.previewTime=.5f;Time.time=50;preview.Sample();float t=AnimationClip.At;Time.time=500;preview.Sample();C(LayerFixture.MatchesClip(preview.View.gameObject,"Pilot_Idle",.25f),"isolated idle final pose uses preview clock");Time.time=501;preview.Sample(false,0,true);C(LayerFixture.MatchesClip(preview.View.gameObject,"Pilot_Idle",.25f),"isolated preview does not sample wall-clock hit reaction");
 Ready();var equipped=Model();equipped.Sample();var baseBlade=Child(equipped.swordRig.gameObject,"Forged Sword").AddComponent<Renderer>();baseBlade.enabled=true;
 var starter=new ItemData{id="starter",name="初行长剑",slot=ItemSlot.Weapon,rarity=Rarity.Common,level=1};
 equipped.ApplyEquipment(starter,null,null);C(equipped.Visible&&!baseBlade.enabled&&equipped.GetComponentsInChildren<Renderer>(true).Where(x=>!x.transform.IsChildOf(equipped.View.transform)&&x.gameObject.activeInHierarchy).All(x=>!x.enabled),"actual supported equipment rebuild hides new procedural renderers");
 equipped.ApplyEquipment(null,null,null);C(equipped.Visible&&!baseBlade.enabled,"actual null equipment refresh cannot re-enable base blade beside pilot");equipped.Unsupported("airborne");equipped.Sample();C(baseBlade.enabled,"fallback restores refreshed null-equipment base visibility");equipped.Unsupported("");equipped.Sample();
 equipped.locomotion.Speed=1;equipped.PlayAction(-1,true,.46f);C(equipped.Visible&&!baseBlade.enabled,"actual moving basic stays on imported layered rig");equipped.Sample(false);equipped.PlayAction(7,false);C(!equipped.Visible,"actual moving skill commit falls back instead of fullbody foot sliding");equipped.locomotion.Speed=0;equipped.PlayAction(-1,true,.46f);C(equipped.Visible,"stationary action restores supported sampled pilot");
 var player=new GameObject("live player").AddComponent<PlayerController>();player.model=equipped;player.TakeDamageFrom(10000,"lethal test");C(player.IsDead&&player.session.Deaths==1&&!equipped.Visible&&!equipped.View.gameObject.activeSelf&&baseBlade.enabled,"actual player lethal damage restores procedural death presentation immediately");C(!equipped.Sample(),"dead model cannot re-enter pilot without further player updates");player.RefreshStats(false);C(!equipped.Sample(),"nonhealing stat refresh cannot revive dead pilot");player.RefreshStats(true);C(!player.IsDead&&equipped.Sample()&&equipped.Visible,"actual healing stat refresh allows reused respawn model to sample again");
 LayerFixture.Run();
 BlenderPilotReadinessTests.Run();
 Console.WriteLine("PASS: "+n+" production Blender adapter/create/sampler/commit/anchor/fallback/ownership checks (managed Unity boundaries)");
 }
}
namespace Emberfall{
 public class EquipmentAppearance{public int Tier;public EquipmentAppearance(ItemData item){}}
 public sealed partial class CombatModel{
 private string equipmentWeaponKey,equipmentArmorKey,equipmentRelicKey;private Transform equipmentWeapon,equipmentArmor,equipmentLeftShoulder,equipmentRightShoulder,equipmentHead,equipmentRelic;private LineRenderer bowstring;
 public void ApplyFashion(object a,object b){}private void RefreshWeaponFashion(){}private void SetBaseCostumeVisible(bool on){}
 private Transform NewGear(string label){var g=new GameObject(label);g.transform.SetParent(transform);g.AddComponent<Renderer>();return g.transform;}
 private void BuildEquipmentWeapon(EquipmentAppearance a){equipmentWeapon=NewGear("built equipment weapon");}private void BuildEquipmentArmor(EquipmentAppearance a){equipmentArmor=NewGear("built equipment armor");}private void BuildEquipmentRelic(EquipmentAppearance a){equipmentRelic=NewGear("built equipment relic");}
 }
 public class Profile{public int level=1,masteryCore=-1;public int[] masteryRanks=new int[4];}public class Progression{public Profile Profile=new Profile();public PlayerStats GetStats()=>new PlayerStats();public object EquippedFashion(FashionSlot slot)=>null;public ItemData Equipped(ItemSlot slot)=>null;}
 public class GameSession{public bool CombatEnded,HasStarted=true;public int Deaths;public Progression Progression=new Progression();public bool HasBlessing(RunBlessing b)=>false;public void RecordIncomingDamage(string s,float d){}public void RecordCombatAction(string s){}public void SpawnFloatingText(Vector3 p,string s,Color c){}public void OnPlayerDied(){Deaths++;CombatEnded=true;}}
 public enum RunBlessing{RiskContract}public enum SoundCue{Hit}public static class GameAudio{public static void Play(SoundCue s){}}public static class AdvancedSkillVfx{public static void Rune(PlayerController h,Vector3 p,float r,Color c,float t,int n){}}public static class CombatFx{public static void Ring(Vector3 p,float r,Color c,float t){}}
 public static class CombatReviewEvents{public static bool Enabled;public static void Emit(string k,int id,float amount=0,string detail=null){}}public static class CombatReviewObjectId{public static int Get(object x)=>1;}public static class WorldTraversal{public static Vector3 NearestWalkable(Vector3 p,float r)=>p;}
 public static class SummonedCompanion{public static void RefreshBuild(PlayerController p){}}public class BuildMastery{public int Core,Tier;public void Configure(int c,int n){}public float WardReduction;public void Reset(){}public float DamageTaken(float x)=>0;}
 public class CancelState{public void Cancel(){}public void Clear(){}}public class RunBonus{public float IncomingDamageMultiplier(float f)=>1;}public class PlayerStats{public float Armor,MaxHealth=100;}
 public partial class PlayerController:MonoBehaviour{
 public GameSession session=new GameSession();public CombatModel model;public float Health=100,MaxHealth=100;public bool IsDead=>Health<=0;public int CombatEpoch;public HeroClass HeroClass=>HeroClass.Vanguard;private PlayerStats stats=new PlayerStats();private BuildMastery masteryCore=new BuildMastery();private CancelState skillBasicRecovery=new CancelState(),targeting,charge;private RunBonus ActiveRunBonuses;private float invulnerability,chargedWardTime,coreWardTime,guardTime,guardReduction,guardRadius,guardPower,healingProtectionTime,healingReduction,passiveTime,passiveReduction,hurtTimer,perfectDodgeCounterTime,focusTime,blinkBufferTime;private int guardRank,guardCastId;private float CombatAttack=1;private bool jumping;private object AimTarget,focusedEnemy;
 private void HitArea(Vector3 p,float r,float d,float k,float s,int c){}private void Heal(float n){}private void TryDefensePassive(){}private void ClearMobilePinnedTarget(){}
 }
}
