using System;using System.Linq;using System.Collections.Generic;using System.Reflection;using UnityEngine;using Emberfall;
namespace UnityEngine{
 public enum RuntimeInitializeLoadType{SubsystemRegistration}public class RuntimeInitializeOnLoadMethodAttribute:Attribute{public RuntimeInitializeOnLoadMethodAttribute(RuntimeInitializeLoadType x){}}
 public class Object{public string name;public bool destroyed;public static GameObject Instantiate(GameObject x,Transform p,bool w)=>x.Clone(p);public static void Destroy(Object x){if(x==null)return;x.destroyed=true;if(x is GameObject g){g.SetActive(false);foreach(var c in g.Components.ToArray())c.GetType().GetMethod("OnDestroy",BindingFlags.Instance|BindingFlags.NonPublic)?.Invoke(c,null);foreach(var t in g.transform.Children.ToArray())Destroy(t.gameObject);}}}
 public class Component:Object{public GameObject gameObject;public Transform transform=>gameObject.transform;public T[] GetComponentsInChildren<T>(bool inactive)where T:Component=>gameObject.GetComponentsInChildren<T>(inactive);}
 public class MonoBehaviour:Component{}
 public class Transform:Component{public Vector3 localPosition,localScale=Vector3.one;public Quaternion localRotation;public Transform parent;public List<Transform> Children=new List<Transform>();public Vector3 position=>parent==null?localPosition:parent.position+localPosition;public void SetParent(Transform p){parent=p;p?.Children.Add(this);}public bool IsChildOf(Transform p)=>this==p||(parent!=null&&parent.IsChildOf(p));public Vector3 TransformPoint(Vector3 p)=>position+p;}
 public class GameObject:Object{public static readonly List<GameObject> All=new List<GameObject>();public readonly List<Component> Components=new List<Component>();public Transform transform;public bool activeSelf=true;public bool activeInHierarchy=>activeSelf&&(transform.parent==null||transform.parent.gameObject.activeInHierarchy);public GameObject(string n=""){All.Add(this);name=n;transform=AddComponent<Transform>();transform.name=n;}public void SetActive(bool a){activeSelf=a;}public T AddComponent<T>()where T:Component,new(){var c=new T{gameObject=this};Components.Add(c);return c;}public T[] GetComponentsInChildren<T>(bool inactive)where T:Component=>Components.OfType<T>().Concat(transform.Children.SelectMany(t=>t.gameObject.GetComponentsInChildren<T>(inactive))).ToArray();public GameObject Clone(Transform p){var g=new GameObject(name);g.transform.SetParent(p);g.transform.localPosition=transform.localPosition;g.transform.localScale=transform.localScale;g.transform.localRotation=transform.localRotation;g.activeSelf=activeSelf;foreach(var c in Components){if(c is Renderer r){var v=g.AddComponent<Renderer>();v.enabled=r.enabled;v.sharedMaterial=r.sharedMaterial;}if(c is MeshFilter m)g.AddComponent<MeshFilter>().sharedMesh=m.sharedMesh;if(c is Animator a){var v=g.AddComponent<Animator>();v.enabled=a.enabled;v.applyRootMotion=a.applyRootMotion;}if(c is Animation a2){var v=g.AddComponent<Animation>();v.enabled=a2.enabled;v.playAutomatically=a2.playAutomatically;}}foreach(var t in transform.Children)t.gameObject.Clone(g.transform);return g;}}
 public class Renderer:Component{public bool enabled=true;public Material sharedMaterial;}public class Material:Object{}public class Mesh:Object{}public class MeshFilter:Component{public Mesh sharedMesh;}public class Animator:Component{public bool enabled=true,applyRootMotion=true;}public class Animation:Component{public bool enabled=true,playAutomatically=true;}
 public class AnimationClip:Object{public float length=2;public static AnimationClip Last;public static float At;public static int Samples;public void SampleAnimation(GameObject g,float t){Last=this;At=t;Samples++;var tip=g.GetComponentsInChildren<Transform>(true).FirstOrDefault(x=>x.name=="Anchor_Tip");if(tip!=null)tip.localPosition=new Vector3(t,1,0);}}
 public static class Resources{public static Dictionary<string,Object> Items=new Dictionary<string,Object>();public static AnimationClip[] Clips=new AnimationClip[0];public static int Loads;public static T Load<T>(string n)where T:Object{Loads++;return Items.TryGetValue(n,out var v)?v as T:null;}public static T[] LoadAll<T>(string n)where T:Object=>Clips.OfType<T>().ToArray();}
 public struct Vector3{public float x,y,z;public Vector3(float a,float b,float c){x=a;y=b;z=c;}public static Vector3 zero=>new Vector3();public static Vector3 one=>new Vector3(1,1,1);public static Vector3 operator +(Vector3 a,Vector3 b)=>new Vector3(a.x+b.x,a.y+b.y,a.z+b.z);}
 public struct Quaternion{public static Quaternion identity=>new Quaternion();}public static class Time{public static float time,deltaTime;public static int frameCount;}public static class Mathf{public static float Abs(float x)=>Math.Abs(x);public static float Min(float a,float b)=>Math.Min(a,b);}
}
namespace Emberfall{
 public enum HeroClass{Vanguard,Arcanist,Ranger,Summoner}
 public sealed partial class CombatModel:MonoBehaviour{
 public HeroClass heroClass;public bool isHero=true,isolatedPreview,actionBasic,dying;public float previewTime,actionDuration,actionAge,recoveryAge=1,smoothedSpeed,gaitPhase;public int actionSkill,actionStartedFrame,weaponActionId,swingCount;public Transform spine,swordRig,staffRig,bowRig,arrowRig;public float phase;public FakeCloth tailoredCloth;public class FakeCloth{public void SetMotion(float a,float b){}}
 public Motion locomotion=new Motion();public class Motion{public float Landing,Side,Forward,Phase,Speed;}
 private Dictionary<string,Material> palette=new Dictionary<string,Material>();private void BeginVisualRecovery(bool ignored){}private void AdvanceVisualMotion(float dt){}
 public void Init(){spine=transform;ConfigureBlenderPilot();}public bool Sample(bool acting=false,float progress=0,bool hurt=false)=>SampleBlenderPilot(acting,progress,hurt);
 public BlenderPilotVisual View=>blenderPilot;public bool Visible=>pilotVisible;
 public void Unsupported(string which){pilotHasGear=which=="gear";pilotHasFashion=which=="fashion";pilotAirborne=which=="airborne";pilotCharging=which=="charge";dying=which=="death";locomotion.Landing=which=="landing"?1:0;locomotion.Side=which=="strafe"?1:0;locomotion.Forward=which=="backwards"?-1:0;}
 }
}
class BlenderPilotAdapterProductionTests{
 static int n;static void C(bool b,string m){n++;if(!b)throw new Exception(m);}static GameObject Child(GameObject root,string name){var g=new GameObject(name);g.transform.SetParent(root.transform);return g;}
 static GameObject Asset(string omit=null){var g=new GameObject("Vanguard");g.AddComponent<Animator>();var inactive=Child(g,"inactive animation");inactive.SetActive(false);inactive.AddComponent<Animation>();g.AddComponent<Renderer>().sharedMaterial=new Material();g.AddComponent<MeshFilter>().sharedMesh=new Mesh();foreach(var x in new[]{"Anchor_Pommel","Anchor_Grip","Anchor_Guard","Anchor_BladeRoot","Anchor_Tip"})if(x!=omit)Child(g,x);return g;}
 static void Ready(string omit=null){Resources.Items.Clear();Resources.Items["BlenderPilot/Vanguard"]=Asset(omit);Resources.Items["BlenderPilot/Pilot_Atlas_Standard"]=new Material();Resources.Clips=new[]{"Pilot_Idle","Pilot_Move","Pilot_Basic","Pilot_Hit","Pilot_Skill"}.Select(x=>new AnimationClip{name=x,length=2}).ToArray();}
 static CombatModel Model(){var root=new GameObject("model");var model=root.AddComponent<CombatModel>();model.heroClass=HeroClass.Vanguard;Child(root,"visible old").AddComponent<Renderer>().enabled=true;Child(root,"hidden old").AddComponent<Renderer>().enabled=false;model.swordRig=Child(root,"procedural sword").transform;model.swordRig.localPosition=new Vector3(-10,0,0);model.Init();return model;}
 static void Main(){
 C(!BlenderPilotArt.Enabled,"pilot disabled on fresh startup");Ready();int loads=Resources.Loads;C(BlenderPilotVisual.Create(null)==null&&Resources.Loads==loads,"disabled pilot never loads assets");
 BlenderPilotArt.Enabled=true;Resources.Items.Clear();C(BlenderPilotVisual.Create(null)==null,"missing model falls back");
 foreach(var socket in new[]{"Anchor_Pommel","Anchor_Grip","Anchor_Guard","Anchor_BladeRoot","Anchor_Tip"}){Ready(socket);C(BlenderPilotVisual.Create(null)==null,"each missing socket falls back");C(!GameObject.All.Any(g=>g.name=="Blender pilot visual (sampled skeleton)"&&!g.destroyed),"missing socket destroys incomplete imported instance");}
 foreach(var clip in new[]{"Pilot_Idle","Pilot_Move","Pilot_Basic","Pilot_Hit","Pilot_Skill"}){Ready();Resources.Clips=Resources.Clips.Where(x=>x.name!=clip).ToArray();C(BlenderPilotVisual.Create(null)==null,"each missing clip falls back");C(!GameObject.All.Any(g=>g.name=="Blender pilot visual (sampled skeleton)"&&!g.destroyed),"missing clip destroys incomplete imported instance");}
 BlenderPilotArt.Enabled=true;typeof(BlenderPilotArt).GetMethod("ResetForPlayerStartup",BindingFlags.Static|BindingFlags.NonPublic).Invoke(null,null);C(!BlenderPilotArt.Enabled,"subsystem startup resets stale opt-in without domain reload");BlenderPilotArt.Enabled=true;Ready();var m=Model();C(m.View!=null&&m.View.Ready,"complete imported asset configures");C(!m.View.gameObject.activeSelf,"imported root stays hidden until first sample");C(m.View.GetComponentsInChildren<Animator>(true).All(a=>!a.enabled&&!a.applyRootMotion)&&m.View.GetComponentsInChildren<Animation>(true).All(a=>!a.enabled&&!a.playAutomatically),"manual sampler disables all automatic drivers including inactive descendants");
 var old=m.GetComponentsInChildren<Renderer>(true).Where(x=>!x.transform.IsChildOf(m.View.transform)).ToArray();C(m.Sample()&&old.All(x=>!x.enabled),"supported pilot hides procedural renderers");
 for(int swing=0;swing<4;swing++){m.swingCount=swing;C(m.WeaponSwingSide==-1,"authored external sword keeps fixed sampled swing side");}
 foreach(float interval in new[]{.18f,.46f,.9f}){Time.frameCount++;int before=AnimationClip.Samples;m.PlayAction(-1,true,interval);C(AnimationClip.Samples==before+1&&AnimationClip.Last.name=="Pilot_Basic"&&Math.Abs(AnimationClip.At/AnimationClip.Last.length-.52f)<.0001f,"actual PlayAction commit samples contact .52 without hidden windup");C(m.TryGetWeaponVisualAnchor(WeaponVisualAnchor.SwordTip,out var anchor)&&Math.Abs(anchor.x-AnimationClip.At)<.0001f,"ribbon anchor reads the sampled external tip");}
 m.PlayAction(7,false);C(AnimationClip.Last.name=="Pilot_Skill","representative skill commit selects imported skill clip");m.locomotion.Speed=1;m.locomotion.Phase=(float)Math.PI;m.Sample();C(AnimationClip.Last.name=="Pilot_Move"&&Math.Abs(AnimationClip.At-1)<.0001f,"movement bridge samples phase through actual imported clip length");m.locomotion.Speed=0;Time.time=2;m.Sample(false,0,true);C(AnimationClip.Last.name=="Pilot_Hit","hurt edge selects imported hit clip");Time.time=2.3f;m.Sample(false,0,false);C(AnimationClip.Last.name=="Pilot_Idle","hurt clip expires into idle");
 foreach(string reason in new[]{"gear","fashion","airborne","charge","death","landing","strafe","backwards","skill"}){m.Unsupported(reason);m.actionBasic=false;m.actionSkill=reason=="skill"?2:7;C(!m.Sample(reason=="skill",.52f),"unsupported states use procedural fallback");C(!m.View.gameObject.activeSelf&&old[0].enabled&&!old[1].enabled,"fallback restores each original renderer enabled state");C(m.TryGetWeaponVisualAnchor(WeaponVisualAnchor.SwordTip,out var a)&&a.x==-10,"hidden pilot does not supply sword anchors");m.Unsupported("");C(m.Sample(),"supported state re-enters pilot");}
 BlenderPilotArt.Enabled=false;C(!m.Sample()&&old[0].enabled&&!old[1].enabled,"runtime opt-out restores originals");for(int swing=0;swing<4;swing++){m.swingCount=swing;C(m.WeaponSwingSide==(swing%2==0?1:-1),"procedural fallback preserves alternating swing side");}BlenderPilotArt.Enabled=true;m.Sample();
 var mesh=m.View.GetComponentsInChildren<MeshFilter>(true)[0].sharedMesh;var material=m.View.GetComponentsInChildren<Renderer>(true)[0].sharedMaterial;C(object.ReferenceEquals(mesh,Resources.Load<GameObject>("BlenderPilot/Vanguard").GetComponentsInChildren<MeshFilter>(true)[0].sharedMesh),"imported mesh remains shared");UnityEngine.Object.Destroy(m.gameObject);C(!mesh.destroyed&&!material.destroyed,"destroying model never owns or destroys imported shared assets");
 Ready();var preview=Model();preview.isolatedPreview=true;preview.previewTime=.5f;Time.time=50;preview.Sample();float t=AnimationClip.At;Time.time=500;preview.Sample();C(AnimationClip.At==t,"isolated idle sample uses preview clock");Time.time=501;preview.Sample(false,0,true);C(AnimationClip.Last.name=="Pilot_Idle"&&AnimationClip.At==t,"isolated preview does not sample wall-clock hit reaction");
 Console.WriteLine("PASS: "+n+" production Blender adapter/create/sampler/commit/anchor/fallback/ownership checks (managed Unity boundaries)");
 }
}
