"""Execute complete status view; independently check actual state notifications/consumption."""
from pathlib import Path
import subprocess,sys,os,tempfile
r=Path(__file__).resolve().parents[1]
with tempfile.TemporaryDirectory(prefix='status-visual-') as t:
 p=Path(t);env=dict(os.environ,DOTNET_CLI_HOME=str(p/'cli'),DOTNET_NOLOGO='1');(p/'NuGet.Config').write_text('<configuration><packageSources><clear/></packageSources></configuration>');(p/'Test.csproj').write_text('<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net8.0</TargetFramework><OutputType>Exe</OutputType></PropertyGroup></Project>')
 for f in ['Assets/Scripts/Combat/EnemyStatusVisual.cs','Assets/Scripts/Core/EnemyStatusVisualRules.cs','Tests/EnemyStatusVisualProductionTests.cs']:(p/Path(f).name).write_text((r/f).read_text())
 def run(expected=None):
  subprocess.run([sys.argv[1],'build',str(p/'Test.csproj'),'--configfile',str(p/'NuGet.Config'),'-v:q'],env=env,check=True);out=subprocess.run([sys.argv[1],str(p/'bin/Debug/net8.0/Test.dll')],env=env,capture_output=True,text=True);print(out.stdout+out.stderr)
  if expected:assert out.returncode and expected in out.stdout+out.stderr
  else:out.check_returncode()
 run();file=p/'EnemyStatusVisualRules.cs';original=file.read_text();file.write_text(original.replace('!frozen||boss','!frozen'));run('boss mark never implies hard freeze');file.write_text(original)
 file=p/'EnemyStatusVisual.cs';original=file.read_text();file.write_text(original.replace('status.VisualStateChanged+=Sync;',''));run('selected real freeze and frost have separate channels');print('PASS compiled boss conflation and lost synchronous binding controls rejected')
ns={'__file__':str(r/'Tests/ConcentratedVenomPoisonTests.py')};exec((r/'Tests/ConcentratedVenomPoisonTests.py').read_text().split('\nwith tempfile.TemporaryDirectory',1)[0],ns)
with tempfile.TemporaryDirectory(prefix='status-authority-') as t:
 p=Path(t);env=dict(os.environ,DOTNET_CLI_HOME=str(p/'cli'),DOTNET_NOLOGO='1');(p/'NuGet.Config').write_text('<configuration><packageSources><clear/></packageSources></configuration>');(p/'Test.csproj').write_text('<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net8.0</TargetFramework><OutputType>Exe</OutputType></PropertyGroup></Project>');(p/'Fixture.cs').write_text(ns['fixture'])
 for f in ['Core/CombatImpactBatch','Core/ScheduledTickWindow','Core/BurnFinaleReceipts','Combat/EnemyStatusEffects','Combat/PlayerController.BurnFeedback','Combat/CombatDamage']:(p/(Path(f).name+'.cs')).write_text((r/'Assets/Scripts'/(f+'.cs')).read_text())
 (p/'Gate.cs').write_text('using System.Collections.Generic;namespace Emberfall{'+ns['member']((r/'Assets/Scripts/Combat/PlayerUpgradeRules.cs').read_text(),'public sealed class RecentCastGate')+'}')
 (p/'Program.cs').write_text('''using System;using System.Reflection;using Emberfall;using UnityEngine;class Program{static void C(bool b,string m){if(!b)throw new Exception(m);}static void Main(){var p=new PlayerController();GameSession.Instance=new GameSession{Player=p};var e=new EnemyController();var s=new EnemyStatusEffects{OwnerEnemy=e};e.StatusEffects=s;typeof(EnemyStatusEffects).GetMethod("Awake",BindingFlags.NonPublic|BindingFlags.Instance).Invoke(s,null);int events=0;bool frozen=false,mark=false,vulnerable=false;s.VisualStateChanged+=()=>{events++;frozen=s.IsFrozen;mark=s.HasFrostMark;vulnerable=s.IsMarked;};s.Freeze(1);C(events==1&&frozen&&mark,"actual Freeze emits granted state synchronously");C(s.TryShatter(p,1)&&!frozen&&!mark&&events==2,"actual shatter emits consumed state synchronously");s.FrostMark(3);C(events==3&&!frozen&&mark,"same frame frost reapply emits new authority");s.Mark(2,.2f);C(events==4&&vulnerable&&!frozen,"vulnerability independent of freeze");GameSession.Instance.InputBlocked=true;Time.deltaTime=5;typeof(EnemyStatusEffects).GetMethod("Update",BindingFlags.NonPublic|BindingFlags.Instance).Invoke(s,null);C(events==4&&mark&&vulnerable,"pause does not expire status or publish false disappearance");GameSession.Instance.InputBlocked=false;typeof(EnemyStatusEffects).GetMethod("Update",BindingFlags.NonPublic|BindingFlags.Instance).Invoke(s,null);C(events==5&&!mark&&!vulnerable,"actual expiry notifies final state");Console.WriteLine("PASS 6 production authority notification checks");}}''')
 run();file=p/'EnemyStatusEffects.cs';original=file.read_text();file.write_text(original.replace('frozenTime = frostMarkTime = 0;\n            NotifyVisualState();','frozenTime = frostMarkTime = 0;'));run('actual shatter emits consumed state synchronously');print('PASS compiled lost consume notification control rejected')
