using System;using System.Linq;using System.Collections.Generic;using System.Text.Json;using UnityEngine;using Emberfall;
class Entry{
 static void C(bool ok,string why){if(!ok)throw new Exception(why);}
 static object Geo(CombatModel m,int hero,int tier,float phase,bool skill)=>new{hero,name=((HeroClass)hero).ToString(),tier,phase,skill,parts=m.GetComponentsInChildren<MeshFilter>(false).Where(f=>f.GetComponent<Renderer>()!=null&&f.GetComponent<Renderer>().enabled&&f.sharedMesh!=null).Select(f=>new{name=f.transform.name,category=m.EnvelopeCategory(f.transform),mesh=f.sharedMesh.name,color=new[]{f.GetComponent<Renderer>().sharedMaterial.color.r,f.GetComponent<Renderer>().sharedMaterial.color.g,f.GetComponent<Renderer>().sharedMaterial.color.b},vertices=f.sharedMesh.vertices.Select(v=>{var w=f.transform.TransformPoint(v);return new[]{w.x,w.y,w.z};}).ToArray(),triangles=f.sharedMesh.triangles}).ToArray(),lines=m.GetComponentsInChildren<LineRenderer>(false).Where(l=>l.enabled).Select(l=>new{width=l.startWidth,color=new[]{l.sharedMaterial.color.r,l.sharedMaterial.color.g,l.sharedMaterial.color.b},points=l.points.Select(v=>{var w=l.transform.TransformPoint(v);return new[]{w.x,w.y,w.z};}).ToArray()}).ToArray()};
 static CombatModel Make(int h,int tier){var m=CombatModel.Hero(new GameObject("actual factory").transform,(HeroClass)h);if(tier==4){m.ApplyEquipment(new ItemData{id="w",slot=ItemSlot.Weapon,level=76,rarity=Rarity.Legendary,upgradeLevel=10},new ItemData{id="a",slot=ItemSlot.Armor,level=76,rarity=Rarity.Legendary,upgradeLevel=10},null);m.ApplyFashion(new FashionData{id="fashion-0-3",slot=FashionSlot.Wings,rarity=Rarity.Legendary},new FashionData{id="fashion-1-3",slot=FashionSlot.Weapon,rarity=Rarity.Legendary});}UnityEngine.Object.Flush();return m;}
 static void Main(){var cases=new List<object>();for(int h=0;h<4;h++)foreach(int tier in new[]{0,4}){var m=Make(h,tier);var identity=m.GetComponentsInChildren<MeshFilter>(true).Select(f=>f.sharedMesh).ToArray();C(identity.Any(mesh=>mesh.name.StartsWith("Blender actor")),"actual original ActorModules loaded");if(h!=0)C(identity.Any(mesh=>mesh.name.StartsWith("F1 silhouette")),"actual F1 body loaded");C(identity.Any(mesh=>mesh.name.StartsWith("Blender weapon")),"actual F3 weapon loaded");if(h==0&&tier==0)C(identity.Count(mesh=>mesh.name.StartsWith("Blender weapon Star"))==4,"actual F3 base sword loaded");
 foreach(float phase in new[]{0f,.16f,BasicActionTimeline.Contact(h==2),.48f,.65f,.83f,1f}){m.EnvelopePose(phase,false);C(identity.SequenceEqual(m.GetComponentsInChildren<MeshFilter>(true).Select(f=>f.sharedMesh)),"all seven action samples keep same body and equipment");cases.Add(Geo(m,h,tier,phase,false));}}
 foreach(int h in new[]{1,2,3}){var m=Make(h,4);float progress=h==2?.28f:.52f;m.EnvelopePose(progress,true);cases.Add(Geo(m,h,4,progress,true));}
 System.IO.File.WriteAllText(@"OUTPUT_PATH",JsonSerializer.Serialize(cases));Console.WriteLine("PASS 59 actual combined factory/F1/F3/Vanguard/equipment/fashion samples: 4 classes x base/T4 x seven real basic timeline samples + 3 actual caster/arrow-draw skill poses; real blade/grip/string contacts, stable mesh identities; NOT Unity");}}
