using System;using System.Linq;using System.IO;using System.Collections.Generic;using System.Reflection;using System.Text.Json;using UnityEngine;using Emberfall;
class FixedSceneryTests {
 static int checks;static void Check(bool v,string s){checks++;if(!v)throw new Exception(s);}static float[] V(Vector3 p)=>new[]{p.x,p.y,p.z};
 static string Nav()=>string.Join(";",WorldTraversal.boxes.Select(x=>string.Join(",",V(x.p))+":"+x.size.x+","+x.size.y))+"/"+string.Join(";",WorldTraversal.circles.Select(x=>string.Join(",",V(x.p))+":"+x.radius));
 static void Main(){string path=Environment.GetEnvironmentVariable("F4_ROOT");foreach(var f in Directory.GetFiles(path+"/Assets/Resources/FixedScenery","*.bytes")){var bytes=File.ReadAllBytes(f);var mesh=AuthoredFixedScenery.Decode(bytes,f);Check(mesh!=null,"actual resource decode "+f);Check(mesh.triangles.Length/3<=2000,"mesh budget");var bad=(byte[])bytes.Clone();Array.Copy(BitConverter.GetBytes(float.NaN),0,bad,12,4);Check(AuthoredFixedScenery.Decode(bad,f)==null,"nonfinite rejection");Check(AuthoredFixedScenery.Decode(bytes.Take(bytes.Length-1).ToArray(),f)==null,"truncation fallback");}Check(AuthoredFixedScenery.Decode(new byte[12],"bad")==null,"bad header fallback");
 var absent=typeof(AuthoredFixedScenery).GetMethod("Load",BindingFlags.Static|BindingFlags.NonPublic).Invoke(null,new object[]{"MissingAsset"});Check(absent==null,"missing resource safe fallback");var fallback=new GameObject("fallback");var original=ProceduralVisuals.Shape(PrimitiveType.Cube);fallback.AddComponent<MeshFilter>().sharedMesh=original;AuthoredFixedScenery.Enabled=false;AuthoredFixedScenery.Apply(fallback,"Column base",PrimitiveType.Cube);Check(ReferenceEquals(original,fallback.GetComponent<MeshFilter>().sharedMesh),"disabled preserves original geometry");Check(!AuthoredFixedScenery.Frame(fallback,1,new Material(Shader.Find("test"))),"disabled frame requests original line");UnityEngine.Object.Destroy(fallback);UnityEngine.Object.Flush();var samples=new List<object>();var before=new List<object>();for(int i=0;i<6;i++){string nav=null,occlusion=null;for(int enabled=0;enabled<2;enabled++){AuthoredFixedScenery.Enabled=enabled==1;WorldTraversal.Reset(ZoneKind.Wilderness);var root=new GameObject("sample "+i);WorldBuilder.FixedSample(root.transform,root.AddComponent<WorldResources>(),i);var renderers=root.GetComponentsInChildren<Renderer>(true);string marks=string.Join(";",root.GetComponentsInChildren<CameraOcclusionSurface>(true).Select(x=>x.transform.name));if(enabled==0){nav=Nav();occlusion=marks;}else{Check(nav==Nav(),"unchanged factory navigation "+i);Check(occlusion==marks,"unchanged factory occlusion registration "+i);Check(renderers.Any(x=>x.GetComponent<MeshFilter>()?.sharedMesh.name.StartsWith("Blender fixed scenery")==true),"factory uses decoded meshes "+i);Check(root.GetComponentsInChildren<Collider>(true).Length==0,"no new collision "+i);}
 var parts=new List<object>();foreach(var rr in renderers){var m=rr.GetComponent<MeshFilter>()?.sharedMesh;if(m==null){if(rr is LineRenderer line && line.enabled){var lc=rr.sharedMaterial.color;parts.Add(new{name=rr.transform.name,mesh="runtime line",vertices=line.points.Select(x=>V(line.useWorldSpace?x:line.transform.TransformPoint(x))).ToArray(),triangles=new int[0],color=new[]{lc.r,lc.g,lc.b},lineWidth=line.widthMultiplier,loop=line.loop});}continue;}var c=rr.sharedMaterial.color;parts.Add(new{name=rr.transform.name,mesh=m.name,vertices=m.vertices.Select(x=>V(rr.transform.TransformPoint(x))).ToArray(),triangles=m.triangles,color=new[]{c.r,c.g,c.b},occluder=rr.GetComponent<CameraOcclusionSurface>()!=null});}(enabled==1?samples:before).Add(new{id=i,parts,rendererCount=renderers.Length,materialInstances=renderers.Select(x=>x.sharedMaterial).Distinct().Count(),authoredTriangles=renderers.Select(x=>x.GetComponent<MeshFilter>()?.sharedMesh).Where(x=>x!=null&&x.name.StartsWith("Blender fixed scenery")).Sum(x=>x.triangles.Length/3)});
 CameraOcclusionSurface.RestoreAll();root.SetActive(false);UnityEngine.Object.Destroy(root);UnityEngine.Object.Flush();}}
 File.WriteAllText(path+"/ArtSource/FixedScenery/factory-before-snapshots.json",JsonSerializer.Serialize(before));File.WriteAllText(path+"/ArtSource/FixedScenery/factory-snapshots.json",JsonSerializer.Serialize(samples));Console.WriteLine("PASS "+checks+" actual decoder/factory/navigation/occlusion checks; managed Unity boundary, not engine acceptance");}
}
