using System;using System.Collections.Generic;using System.Reflection;using Emberfall;using UnityEngine;
namespace UnityEngine
{
 public class Object{public static void Destroy(Object o){}}
 public class MonoBehaviour:Object{public GameObject gameObject=new GameObject();public Transform transform=>gameObject.transform;}
 public class GameObject:Object{public bool activeInHierarchy=true;public Transform transform=new Transform();public void SetActive(bool v){activeInHierarchy=v;}}
 public class Transform{public Vector3 position,forward=new Vector3(0,0,1),localScale=Vector3.one;public Quaternion rotation;}
 public struct Quaternion{public static Quaternion LookRotation(Vector3 v)=>new Quaternion();}
 public struct Color{public Color(float r,float g,float b,float a=1){}}
 public struct Bounds{public Vector3 min,max;public Bounds(Vector3 p){min=p-new Vector3(.5f,0,.5f);max=p+new Vector3(.5f,2,.5f);}}
 public struct Vector2{public float x,y;public Vector2(float a,float b){x=a;y=b;}public static Vector2 zero=>new Vector2();public float magnitude=>(float)Math.Sqrt(x*x+y*y);public static float Distance(Vector2 a,Vector2 b)=>(a-b).magnitude;public static Vector2 operator-(Vector2 a,Vector2 b)=>new Vector2(a.x-b.x,a.y-b.y);public static Vector2 operator/(Vector2 a,float b)=>new Vector2(a.x/b,a.y/b);public static Vector2 operator*(Vector2 a,float b)=>new Vector2(a.x*b,a.y*b);}
 public struct Vector3{public float x,y,z;public Vector3(float a,float b,float c){x=a;y=b;z=c;}public static Vector3 zero=>new Vector3();public static Vector3 up=>new Vector3(0,1,0);public static Vector3 one=>new Vector3(1,1,1);public float sqrMagnitude=>x*x+y*y+z*z;public float magnitude=>(float)Math.Sqrt(sqrMagnitude);public Vector3 normalized=>magnitude>0?this/magnitude:zero;public static float Angle(Vector3 a,Vector3 b){return (float)(Math.Acos(Math.Clamp((a.x*b.x+a.y*b.y+a.z*b.z)/Math.Max(.0001f,a.magnitude*b.magnitude),-1,1))*180/Math.PI);}public static Vector3 ClampMagnitude(Vector3 v,float m)=>v.magnitude>m?v.normalized*m:v;public static Vector3 operator+(Vector3 a,Vector3 b)=>new Vector3(a.x+b.x,a.y+b.y,a.z+b.z);public static Vector3 operator-(Vector3 a,Vector3 b)=>new Vector3(a.x-b.x,a.y-b.y,a.z-b.z);public static Vector3 operator*(Vector3 a,float b)=>new Vector3(a.x*b,a.y*b,a.z*b);public static Vector3 operator/(Vector3 a,float b)=>new Vector3(a.x/b,a.y/b,a.z/b);public static implicit operator Vector2(Vector3 a)=>new Vector2(a.x,a.y);}
 public struct Rect{public float x,y,width,height;public Rect(float a,float b,float c,float d){x=a;y=b;width=c;height=d;}public float xMin=>x;public float xMax=>x+width;public float yMin=>y;public float yMax=>y+height;public static Rect MinMaxRect(float a,float b,float c,float d)=>new Rect(a,b,c-a,d-b);public bool Contains(Vector2 p)=>p.x>=x&&p.x<xMax&&p.y>=y&&p.y<yMax;public bool Overlaps(Rect r)=>x<r.xMax&&xMax>r.x&&y<r.yMax&&yMax>r.y;public static bool operator==(Rect a,Rect b)=>a.x==b.x&&a.y==b.y&&a.width==b.width&&a.height==b.height;public static bool operator!=(Rect a,Rect b)=>!(a==b);public override bool Equals(object o)=>o is Rect r&&this==r;public override int GetHashCode()=>0;}
 public static class Mathf{public static float Clamp(float v,float a,float b)=>Math.Clamp(v,a,b);public static float Clamp01(float v)=>Clamp(v,0,1);public static float Max(float a,float b)=>Math.Max(a,b);public static float Min(float a,float b)=>Math.Min(a,b);public static float Lerp(float a,float b,float t)=>a+(b-a)*t;}
 public enum TouchPhase{Began,Moved,Stationary,Ended,Canceled}public struct Touch{public int fingerId;public TouchPhase phase;public Vector2 position;}
 public static class Input{public static bool mousePresent;public static List<Touch> touches=new List<Touch>();public static int touchCount=>touches.Count;public static Touch GetTouch(int i)=>touches[i];public static bool GetMouseButton(int i)=>false;public static bool GetMouseButtonDown(int i)=>false;public static bool GetMouseButtonUp(int i)=>false;public static Vector3 mousePosition;}
 public static class Screen{public static float height=320;}public static class Time{public static int frameCount;public static float deltaTime;}
 public struct Ray{public Vector3 GetPoint(float v)=>new Vector3();}public struct Plane{public Plane(Vector3 a,Vector3 b){}public bool Raycast(Ray r,out float t){t=1;return true;}}
 public class Camera{public static Camera main=new Camera();public Rect pixelRect=new Rect(0,0,568,320);public float nearClipPlane=.1f;public Vector3 WorldToScreenPoint(Vector3 p)=>new Vector3(280+p.x*10,160+p.z*10+p.y*3,10+p.z);public Ray ScreenPointToRay(Vector2 p)=>new Ray();public T GetComponent<T>()where T:new()=>new T();}
}
namespace Emberfall
{
 public class EnemyController{public GameObject gameObject=new GameObject();public Transform transform=>gameObject.transform;public bool IsDead,IsBoss;public float HitFootprintBonus;public EnemyController(float z){transform.position=new Vector3(0,0,z);}}
 public static class CombatFx{public static Vector3 Flat(Vector3 v)=>new Vector3(v.x,0,v.z);public static void WeaponSlash(params object[] p){}}
 public static class CombatSight{public static bool Visible=true;public static bool Direct(Vector3 a,Vector3 b)=>Visible;public static Vector3 GroundPoint(Vector3 a,Vector3 b)=>Visible?b:a;}
 public class FakeProgression{public GameProfile Profile=new GameProfile{skillRanks=new int[10]};}
 public class GameSession{public PlayerController Player;public bool HasStarted=true,InputBlocked;public float ArenaRadius=25;public List<EnemyController> Enemies=new List<EnemyController>();public FakeProgression Progression=new FakeProgression();public string Failure;public void ReportControlFailure(string key,string s){Failure=key+":"+s;}public void RecordClassTutorial(HeroClass h){}public void RecordCombatAction(string s){}public void SpawnMechanismText(Vector3 p,string s,Color c){}}
 public class GameUI{public bool LifecycleTouchBlocked,CompanionCommandsVisible,Overlay;public void RefreshTouchViewport(){}public bool TryBeginTouchSkill(int f,Vector2 p)=>p.x>500&&p.y>250;public void UpdateTouchSkill(int f,Vector2 p,bool e,bool c){}public bool IsScreenPointOverUI(Vector2 p)=>Overlay||p.x<45;public void ActivateFreeCommand(bool b){}public void ActivateMobileInteraction(int f){}public void CancelMobileCast(){}}
 public class AdventureCamera{public static float Pitch;public void ApplyMobilePitch(float d){Pitch+=d;}}
 public class Recovery{public bool Blocked;}public class Model{public void PlayAction(int s,bool a,float c){}}
 public class Bonus{public float AttackSpeedMultiplier=1;}
 public struct CombatDamage{}public enum SoundCue{Attack}public static class GameAudio{public static void Play(SoundCue c){}}
 public static class PlayerUpgradeRules{public static float CounterAfterAttack(float a,float b,bool hit)=>b;}
 public static class CombatProjectile{public static int Shots;public static EnemyController Last;public static void BasicShot(PlayerController p,GameSession s,Vector3 a,Vector3 b,CombatDamage d,Color c,bool r,EnemyController e){Shots++;Last=e;}}
 public static class CombatReviewEvents{public static bool Enabled=false;public static void Emit(string name,int id,int skill=0){}}public static class CombatReviewObjectId{public static int Get(object o)=>1;}
 public static class SummonedCompanion{public static EnemyController Team;public static int Commands;public static EnemyController ExplicitFocus(PlayerController p)=>Team;}
 public class AdvancedSkillVfx:MonoBehaviour{public static AdvancedSkillVfx Rune(params object[] a)=>new AdvancedSkillVfx();}
 public sealed partial class PlayerController:MonoBehaviour
 {
  public GameSession session;public HeroClass HeroClass=HeroClass.Arcanist;public bool IsDead,TraversalStartedThisFrame;public int CombatEpoch=1;public EnemyController AimTarget,FocusTarget;public Vector3 aimPoint;public Vector3 AimPoint=>aimPoint;
  public SkillChargeController charge;public SkillTargetingController targeting;public int Casts;public Vector3 LastCast;public float Energy=100;public EnemyController LastCastEnemy;
  readonly List<MobileSkillPolicy.Candidate> mobileAimCandidates=new List<MobileSkillPolicy.Candidate>();Recovery skillBasicRecovery=new Recovery();Model model=new Model();Bonus ActiveRunBonuses;float attackCooldown,mobilityTime,attackAnimation,counterTime,perfectDodgeCounterTime;int mobilityRank;bool lastMeleeDamagedEnemy,executingChargedSkill;
  public PlayerController(GameSession s){session=s;s.Player=this;charge=new SkillChargeController();charge.Initialize(this,s);targeting=new SkillTargetingController(this,s);for(int i=0;i<10;i++)s.Progression.Profile.skillRanks[i]=1;}
  public T GetComponent<T>()where T:class=>typeof(T)==typeof(SkillChargeController)?charge as T:targeting as T;
  Bounds EnemyAimBounds(EnemyController e)=>new Bounds(e.transform.position);Vector3 EnemyBodyPoint(EnemyController e)=>e.transform.position+Vector3.up;void PruneAimGeometry(){}
  public bool CanBeginSkillTargeting(int skill)=>!session.InputBlocked&&!IsDead&&Energy>=10;void CastSkill(int skill){Casts++;Energy-=10;LastCast=aimPoint;LastCastEnemy=charge.TargetEnemy;}public void CancelCombatPose(){}
  CombatDamage Damage(float n)=>new CombatDamage();bool HasMechanic(EquipmentMechanic m)=>false;bool Melee(float r,float a,CombatDamage d,float k,float s,bool basic=false)=>false;
  public Vector3 Aim(Vector3 movement)=>ResolveMobileAim(movement);public void Attack()=>BasicAttack();public void AdvanceCharge(float dt){typeof(SkillChargeController).GetMethod("Advance",BindingFlags.Instance|BindingFlags.NonPublic).Invoke(charge,new object[]{dt});}
 }
 public partial class SkillTargetingController
 {
  PlayerController owner;GameSession session;int skill=-1,epoch,cancelledFrame=-1,castFrame=-1;bool previewDirty;GameObject visuals;public bool IsTargeting=>skill>=0;public Preview CurrentPreview;public Vector3 TargetPoint;public bool ConfirmingContract;public SkillTargetingController(PlayerController p,GameSession s){owner=p;session=s;}void EnsureVisuals(){visuals=new GameObject();}public void SetTarget(Vector3 p){TargetPoint=p;}public bool Confirm()=>true;
 }
 public sealed partial class MobileControls
 {
  enum Role{Move,Attack,Skill,Aim,Camera,Consumed}readonly Dictionary<int,Role> fingers=new Dictionary<int,Role>();readonly MobileCameraGesture cameraGesture=new MobileCameraGesture();readonly List<int> staleFingers=new List<int>();static MobileControls instance;GameSession session;GameUI ui;int moveFinger=-1000;Vector2 joystickOrigin;bool hasJoystickOrigin;PlayerController worldPointerOwner;EnemyController worldPointerTarget;int worldPointerEpoch;Rect lastSafe;
  public static bool Active=true,SimulationEnabled;public static Vector2 Move;public static bool AttackHeld;static bool dodge,potion,jump;public static MobileControlLayout Layout=new MobileControlLayout(568,320,160);public static Rect SafeArea=new Rect(0,0,568,320);float Scale=>Layout.Scale;Vector2 ToUI(Vector2 p)=>new Vector2(p.x,320-p.y)/Scale;static Rect Area(MobileControlLayout.Area a)=>new Rect(a.X,a.Y,a.Width,a.Height);Rect Attack=>Area(Layout.Attack);Rect Dodge=>Area(Layout.Dodge);Rect Potion=>Area(Layout.Potion);Rect Jump=>Area(Layout.Jump);Rect Cancel=>Area(Layout.Cancel);bool CanCancel=>session.Player.charge.IsCharging;
  public MobileControls(GameSession s,GameUI u){session=s;ui=u;instance=this;lastSafe=SafeArea;}void CheckDodgeFeedback(){}void CheckPotionFeedback(){}public static bool IsScreenPointOverControls(Vector2 p){var v=instance.ToUI(p);return Area(Layout.MoveZone).Contains(v)||instance.Attack.Contains(v)||instance.Dodge.Contains(v)||instance.Potion.Contains(v)||instance.Jump.Contains(v)||instance.Cancel.Contains(v);}
  public void Tick()=>Update();public Vector2 Control(MobileControlLayout.Area a)=>new Vector2((a.X+a.Width/2)*Scale,320-(a.Y+a.Height/2)*Scale);
 }
}
public static class MobilePinnedTargetProductionTests
{
 static int n;static void Check(bool b,string m){n++;if(!b)throw new Exception(m);}static Vector2 ScreenEnemy(EnemyController e)=>Camera.main.WorldToScreenPoint(e.transform.position+Vector3.up);
 static void Tap(MobileControls c,int f,Vector2 p){c.ProcessPointer(f,TouchPhase.Began,p);c.ProcessPointer(f,TouchPhase.Ended,p);}
 public static string Run()
 {
  n=0;Time.frameCount=1;var s=new GameSession();var hero=new PlayerController(s);var ui=new GameUI();var controls=new MobileControls(s,ui);var a=new EnemyController(8);var b=new EnemyController(2);s.Enemies.Add(a);s.Enemies.Add(b);var p=ScreenEnemy(a);
  controls.ProcessPointer(11,TouchPhase.Began,controls.Control(MobileControls.Layout.Joystick));Tap(controls,12,p);Check(hero.MobilePinnedTarget==a,"joystick and separate tap select actual projected enemy");hero.Aim(new Vector3(0,0,-1));Check(hero.AimTarget==a,"movement and closer enemy cannot replace pin");hero.Attack();Check(CombatProjectile.Last==a,"actual basic attack uses pinned enemy");hero.PrepareMobileSkillAim(1);Check(hero.AimTarget==a&&hero.AimPoint.z==8,"actual skill preparation shares pinned intent");
  hero.PinMobileTarget(null);controls.ProcessPointer(12,TouchPhase.Began,p);controls.ProcessPointer(12,TouchPhase.Moved,new Vector2(p.x+20,p.y));controls.ProcessPointer(12,TouchPhase.Moved,p);controls.ProcessPointer(12,TouchPhase.Ended,p);Check(hero.MobilePinnedTarget==null,"horizontal out-and-back never taps");
  foreach(Vector2 move in new[]{new Vector2(0,20),new Vector2(8,8)}){controls.ProcessPointer(12,TouchPhase.Began,p);controls.ProcessPointer(12,TouchPhase.Moved,new Vector2(p.x+move.x,p.y+move.y));controls.ProcessPointer(12,TouchPhase.Ended,p);Check(hero.MobilePinnedTarget==null,"vertical and diagonal drag never tap");}
  controls.ProcessPointer(12,TouchPhase.Began,p);controls.ProcessPointer(13,TouchPhase.Ended,p);Check(hero.MobilePinnedTarget==null,"nonowner release cannot submit tap");controls.ProcessPointer(12,TouchPhase.Canceled,p);Check(hero.MobilePinnedTarget==null,"canceled pointer never pins");
  controls.ProcessPointer(12,TouchPhase.Began,p);controls.ProcessPointer(13,TouchPhase.Began,controls.Control(MobileControls.Layout.Attack));controls.ProcessPointer(12,TouchPhase.Ended,p);Check(hero.MobilePinnedTarget==null,"action finger preempts world candidate");MobileControls.ResetInput();
  controls.ProcessPointer(12,TouchPhase.Began,new Vector2(10,100));controls.ProcessPointer(12,TouchPhase.Ended,p);Check(hero.MobilePinnedTarget==null,"UI-started pointer never becomes world tap");controls.ProcessPointer(12,TouchPhase.Began,p);controls.ProcessPointer(12,TouchPhase.Ended,new Vector2(10,100));Check(hero.MobilePinnedTarget==null,"release over UI never commits");
  controls.ProcessPointer(12,TouchPhase.Began,p);hero.CombatEpoch++;controls.ProcessPointer(12,TouchPhase.Ended,p);Check(hero.MobilePinnedTarget==null,"room epoch cancels pending world pointer");controls.ProcessPointer(12,TouchPhase.Began,p);controls.Tick();controls.ProcessPointer(12,TouchPhase.Ended,p);Check(hero.MobilePinnedTarget==null,"missing touch is cancelled through real Update");
  Tap(controls,12,p);Check(hero.MobilePinnedTarget==a,"fresh pointer can pin after cancellation");Tap(controls,12,new Vector2(220,180));Check(hero.MobilePinnedTarget==null,"empty world tap clears pin");
  controls.ProcessPointer(12,TouchPhase.Began,p);controls.ProcessPointer(13,TouchPhase.Began,new Vector2(10,100));controls.ProcessPointer(12,TouchPhase.Ended,p);Check(hero.MobilePinnedTarget==null,"another UI pointer cancels candidate");
  controls.ProcessPointer(12,TouchPhase.Began,p);ui.LifecycleTouchBlocked=true;controls.ProcessPointer(12,TouchPhase.Ended,p);ui.LifecycleTouchBlocked=false;Check(hero.MobilePinnedTarget==null,"viewport/background lifecycle block discards candidate");
  controls.ProcessPointer(12,TouchPhase.Began,p);s.InputBlocked=true;controls.Tick();s.InputBlocked=false;controls.ProcessPointer(12,TouchPhase.Ended,p);Check(hero.MobilePinnedTarget==null,"pause interrupt requires fresh world down");
  controls.ProcessPointer(12,TouchPhase.Began,p);controls.ProcessPointer(12,TouchPhase.Ended,ScreenEnemy(b));Check(hero.MobilePinnedTarget==null,"start and release must resolve same projected identity");
  for(int density=1;density<=3;density++){var gesture=new MobileCameraGesture();gesture.Begin(8,100,100);gesture.Move(8,100+9*density,100,density,false,false);gesture.Move(8,100,100,density,true,false);Check(!gesture.TapCompleted,"horizontal threshold scales by actual logical density");}
  var overlap=new EnemyController(8);s.Enemies.Add(overlap);Check(hero.PickMobileTarget(p)==a,"exact projected overlap preserves stable session order");s.Enemies.Remove(overlap);
  hero.PinMobileTarget(a);CombatSight.Visible=false;int shots=CombatProjectile.Shots;hero.Attack();Check(CombatProjectile.Shots==shots&&s.Failure=="attack:目标被遮挡"&&hero.MobilePinnedTarget==a,"occlusion refuses basic attack without replacing intent");float energy=hero.Energy;Check(!hero.targeting.Begin(1)&&!hero.charge.IsCharging&&hero.Energy==energy&&hero.Casts==0&&hero.MobilePinnedTarget==a,"blocked pin rejects actual targeted skill without charge or resource spending");CombatSight.Visible=true;
  a.transform.position=new Vector3(0,0,12);Check(!hero.targeting.Begin(1)&&s.Failure=="skill1:距离不足"&&hero.MobilePinnedTarget==a,"skill range failure retains valid general-scope pin");
  a.transform.position=new Vector3(0,0,8);Time.frameCount++;Check(hero.targeting.Begin(1)&&hero.charge.IsCharging,"actual targeting begins charge from pinned point");var captured=hero.charge.TargetPoint;hero.PinMobileTarget(b);Check(hero.charge.TargetPoint.z==captured.z,"new pin never changes captured charge point");hero.AdvanceCharge(20);Check(hero.Casts==1&&hero.LastCast.z==captured.z&&hero.MobilePinnedTarget==b,"actual charge release ignores later pin and uses snapshot");
  Time.frameCount++;hero.PinMobileTarget(a);a.IsDead=true;hero.Aim(Vector3.one);Check(hero.MobilePinnedTarget==null&&hero.AimTarget==b,"dead pin clears and automatic targeting recovers");a.IsDead=false;hero.PinMobileTarget(a);s.Enemies.Remove(a);Check(hero.MobilePinnedTarget==null,"removed target clears scope");s.Enemies.Add(a);hero.PinMobileTarget(a);a.transform.position=new Vector3(0,0,15);Check(hero.MobilePinnedTarget==null,"same existing14m scope expires pin");a.transform.position=new Vector3(0,0,8);hero.PinMobileTarget(a);hero.CombatEpoch++;Check(hero.MobilePinnedTarget==null,"new combat epoch clears pin");
  hero.HeroClass=HeroClass.Summoner;hero.PinMobileTarget(a);SummonedCompanion.Team=b;hero.PrepareMobileSkillAim(9);Check(hero.AimTarget==b&&hero.MobilePinnedTarget==a&&SummonedCompanion.Commands==0,"ordinary contract preview follows explicit team without pin commanding pets");Time.frameCount++;Check(hero.targeting.Begin(9)&&hero.charge.TargetEnemy==b,"ordinary contract charge owns same explicit team intention");
  return "PASS: "+n+" actual pointer/aim/basic/targeting/charge assertions (managed scene doubles, not touch-device delivery)";
 }
}
