using System;using System.Linq;using System.Reflection;using UnityEngine;using Emberfall;
class ProtectionPresentationTests {
 static int checks;static void C(bool b,string msg){checks++;if(!b)throw new Exception(msg);}
 static PlayerController New(){foreach(var o in GameObject.All.ToArray())UnityEngine.Object.Destroy(o);UnityEngine.Object.Flush();foreach(var x in new[]{typeof(FilledSkillVfx),typeof(AdvancedSkillVfx),typeof(CombatVisualLease)})x.GetMethod(x==typeof(FilledSkillVfx)?"ResetAssets":x==typeof(AdvancedSkillVfx)?"ResetCount":"Reset",BindingFlags.Static|BindingFlags.NonPublic).Invoke(null,null);UnityEngine.Object.Flush();Time.deltaTime=0;Resources.Bad=null;SummonedCompanion.active.Clear();var h=new GameObject("hero").AddComponent<PlayerController>();GameSession.Instance=new GameSession{Player=h,HasStarted=true};return h;}
 static AdvancedSkillVfx Anchor()=>GameObject.All.Last(o=>o.activeInHierarchy&&!o.Destroyed&&o.GetComponent<AdvancedSkillVfx>()!=null).GetComponent<AdvancedSkillVfx>();
 static FilledSkillVfx Child(AdvancedSkillVfx a)=>GameObject.All.Single(o=>o.transform.parent==a.transform&&o.GetComponent<FilledSkillVfx>()!=null).GetComponent<FilledSkillVfx>();
 static MeshRenderer Part(FilledSkillVfx f)=>GameObject.All.Single(o=>o.transform.parent==f.transform&&o.GetComponent<MeshRenderer>()!=null).GetComponent<MeshRenderer>();
 static int Pulses()=>GameObject.All.Count(o=>o.activeInHierarchy&&!o.Destroyed&&o.GetComponent<MeshRenderer>()!=null&&o.GetComponent<MeshRenderer>().EnvelopeMode==4);
 static void Main(string[] args){Resources.Root=args[0];var color=new Color(.5f,.9f,1);
 foreach(var hero in (HeroClass[])Enum.GetValues(typeof(HeroClass))) foreach(bool low in new[]{false,true}) {
  var h=New();h.HeroClass=hero;Application.isMobilePlatform=EffectPreferences.ReducedEffects=low;
  bool alive=true;var g=AdvancedSkillVfx.Protection(h,Vector3.zero,2.1f,color,6,1,()=>alive);var gf=Child(g);var gp=Part(gf);
  C(gp.EnvelopeMode==1&&gp.TintAlpha>0,"guard stable outline visible at birth");var scale=gp.transform.localScale;float alpha=gp.TintAlpha;Time.deltaTime=.75f;gf.gameObject.Call("Update");C(gp.TintAlpha==alpha&&gp.transform.localScale.x==scale.x&&gp.transform.localScale.y==scale.y,"guard intensity and certified envelope stable");
  var passive=AdvancedSkillVfx.Protection(h,Vector3.zero,2.1f,color,5,1,()=>alive,true);var pf=Child(passive);var pp=Part(pf);C(pp.EnvelopeMode==2,"passive identity channel distinct");float bright=pp.TintAlpha;Time.deltaTime=.4f;pf.gameObject.Call("Update");C(pp.TintAlpha<bright&&pp.TintAlpha<gp.TintAlpha,"one passive reveal settles below guard intensity");C(pp.transform.localScale.x==scale.x&&pp.transform.localScale.y==scale.y,"passive never shrinks through actor");
  var seq=new GameObject("actual healing").AddComponent<HealingProbe>();seq.Setup(h,1,false);var heal=Anchor();var hf=Child(heal);var hp=Part(hf);C(hp.EnvelopeMode==3&&hp.TintAlpha<gp.TintAlpha&&g.gameObject.activeInHierarchy&&passive.gameObject.activeInHierarchy,"healing flow distinct and independent channels");
  h.Health=h.MaxHealth;seq.Tick(1);C(Pulses()==0,"full HP produces no healing-success pulse");C(heal.gameObject.activeInHierarchy&&hp.Opacity>0,"full HP keeps true ongoing state");
  h.Health=99.75f;seq.Tick(1);C(h.Health==100&&Math.Abs(GameSession.Instance.ActualHealed-.25f)<.001f,"actual clamped quarter HP gain");C(Pulses()==1,"positive actual gain emits one short success pulse");
  h.transform.position=new Vector3(2,0,3);Time.deltaTime=.1f;heal.gameObject.Call("Update");C(heal.transform.position.x==2&&heal.transform.position.z==3,"healing state follows owner");
  seq.gameObject.SetActive(false);C(!heal.gameObject.activeSelf,"sequence disable immediately releases healing state");C(g.gameObject.activeSelf&&passive.gameObject.activeSelf,"healing termination does not cancel guard or passive");
  GameSession.Instance.InputBlocked=true;Time.deltaTime=0;alive=false;g.gameObject.Call("Update");passive.gameObject.Call("Update");C(!g.gameObject.activeSelf&&!passive.gameObject.activeSelf,"paused false states clear");
 }
 Application.isMobilePlatform=EffectPreferences.ReducedEffects=false;
 foreach(var hero in (HeroClass[])Enum.GetValues(typeof(HeroClass)))foreach(bool restricted in new[]{false,true})foreach(int rank in new[]{1,2,3}) {
  var h=New();h.HeroClass=hero;h.Health=1;SummonedCompanion.Healed=0;var q=new GameObject("sequence").AddComponent<HealingProbe>();q.Setup(h,rank,restricted);q.Tick(.99f);C(h.Health==1,"no early heal");q.Tick(.01f);for(int i=0;i<4;i++)q.Tick(1);
  float total=restricted?(rank==3?80:rank==2?70:60):rank==3?55:rank==2?42:30;C(Math.Abs(h.Health-(1+total))<.001f,"original five pulse amount and timing");C(h.skillRuntime.Energy==(rank==3?8:0),"rank3 final energy unchanged");C(Math.Abs(SummonedCompanion.Healed-(hero==HeroClass.Summoner?(rank==3?.55f:rank==2?.42f:.3f):0))<.001f,"companion heal amount unchanged");UnityEngine.Object.Flush();C(!GameObject.All.Any(o=>o.activeInHierarchy&&!o.Destroyed&&o.GetComponent<AdvancedSkillVfx>()!=null),"normal completion clears persistent healing");
 }
 {var h=New();h.HeroClass=HeroClass.Summoner;h.Health=100;var wounded=new GameObject("wounded pet").AddComponent<SummonedCompanion>();wounded.Owner=h;wounded.session=GameSession.Instance;wounded.Health=99.5f;wounded.transform.position=new Vector3(4,0,2);SummonedCompanion.active.Add(wounded);var full=new GameObject("full pet").AddComponent<SummonedCompanion>();full.Owner=h;full.session=GameSession.Instance;full.Health=100;SummonedCompanion.active.Add(full);var q=new GameObject("healing").AddComponent<HealingProbe>();q.Setup(h,1,false);q.Tick(1);C(h.Health==100&&wounded.Health==100&&Pulses()==1,"full caster wounded companion heals only real recipient");C(!GameObject.All.Any(o=>o.activeInHierarchy&&o.GetComponent<FilledSkillVfx>()!=null&&o.transform.parent==full.transform),"full companion has no false pulse");var pulse=GameObject.All.Single(o=>o.activeInHierarchy&&o.GetComponent<FilledSkillVfx>()!=null&&o.transform.parent==wounded.transform);C(pulse.transform.position.x==4&&pulse.transform.position.z==2,"companion pulse follows actual recipient position");}
 foreach(bool epoch in new[]{false,true}){var h=New();var q=new GameObject("sequence").AddComponent<HealingProbe>();q.Setup(h,1,false);var a=Anchor();GameSession.Instance.InputBlocked=true;if(epoch)h.CombatEpoch++;else h.IsDead=true;Time.deltaTime=0;a.gameObject.Call("Update");C(!a.gameObject.activeSelf&&CombatVisualLease.Active==0,"paused death or epoch immediately clears healing");}
 {var h=New();var old=new GameObject("old").AddComponent<HealingProbe>();old.Setup(h,1,false);var previous=Anchor();var fresh=new GameObject("fresh").AddComponent<HealingProbe>();fresh.Setup(h,1,false);var current=Anchor();old.gameObject.SetActive(false);UnityEngine.Object.Flush();C(!previous.gameObject.activeSelf&&current.gameObject.activeInHierarchy,"same frame healing refresh survives old sequence cleanup");}
 {var h=New();var a=AdvancedSkillVfx.Healing(h,2.1f,color,5,1,()=>true);var f=Child(a);var part=Part(f);f.Retire();C(part.EnvelopeMode==0,"rental reset removes envelope mode");FilledSkillVfx.Charge(null,h,Vector3.zero,2,color,1,4);var reused=GameObject.All.Last(o=>o.activeInHierarchy&&o.GetComponent<FilledSkillVfx>()!=null).GetComponent<FilledSkillVfx>();C(ReferenceEquals(f,reused)&&Part(reused).EnvelopeMode==0,"generic charge unchanged after healing rental");}
 Console.WriteLine("PASS "+checks+" actual guard/passive/sequence-Heal/MPB/lifetime assertions; real authored bytes, managed scene boundaries, not Unity rendering.");}
}
