using System;using Emberfall;using UnityEngine;
public static class RoomBranchProductionTests{
 static int n;static void C(bool b,string m){n++;if(!b)throw new Exception(m);}
 static void Complete(GameSession s){var p=s.RoomChainRun.Room;foreach(var e in s.Enemies)s.Kill(e);if(!p.Boss&&!p.Interlude){if(p.Objective==RoomObjective.Purify){for(int seal=0;seal<2;seal++){s.Player.Teleport(s.Markers[seal].transform.position);for(int i=0;i<12;i++)s.Tick();}}else if(p.Objective==RoomObjective.Escape){s.Player.Teleport(new Vector3(0,0,11));for(int i=0;i<16;i++)s.Tick();}}}
 static void Door(GameSession s){s.Player.Teleport(new Vector3(0,0,14));}
 public static void Main(){
 for(int seed=0;seed<54;seed++)foreach(RoomBranch branch in new[]{RoomBranch.Seal,RoomBranch.Supply}){
 var s=new GameSession(seed);int originalTier=s.DungeonTier;bool originalLimited=s.ChallengeRun;var run=s.RoomChainRun;C(!s.ConfirmRoomBranch(branch),"early branch rejected");Complete(s);s.Tick();s.Tick();C(s.ConfirmBlessingForTest(0),"first blessing remains");Door(s);C(s.EnterNextRoom()&&run.Room.Index==1,"first transition real host");Complete(s);Door(s);var old=run.Room;int epoch=s.Player.CombatEpoch,count=s.Enemies.Count;
 C(!s.EnterNextRoom()&&s.RoomBranchChoiceOpen&&s.InputBlocked&&Time.timeScale==0,"second door opens blocked selection without generation");C(ReferenceEquals(old,run.Room)&&count==s.Enemies.Count&&epoch==s.Player.CombatEpoch,"unselected branch never generated");
 s.CancelRoomBranchChoice();C(!s.RoomBranchChoiceOpen&&ReferenceEquals(old,run.Room)&&run.SelectedBranch==RoomBranch.None,"back preserves second room and no selection");C(!s.EnterNextRoom()&&s.RoomBranchChoiceOpen,"reopen choice");s.Paused=true;C(!s.ConfirmRoomBranch(branch),"pause blocks selection");s.Paused=false;s.Background(true);C(!s.ConfirmRoomBranch(branch)&&s.RoomBranchChoiceOpen,"background preserves undecided choice");s.Background(false);s.Progression.Fail=true;C(!s.ConfirmRoomBranch(branch)&&run.SelectedBranch==RoomBranch.None&&s.RoomBranchChoiceOpen,"failed save retains undecided live room");s.Progression.Fail=false;
 C(s.ConfirmRoomBranch(branch),"confirm transitions actual host");C(run.Room.Index==2&&run.Room.Branch==branch&&run.Room.Objective==(branch==RoomBranch.Seal?RoomObjective.Purify:RoomObjective.Hunt),"selected objective replaces old seed objective");C(!run.Failed&&s.Enemies.Count==(branch==RoomBranch.Seal?4:6),"only selected finite roster spawned reachable");C(!s.ConfirmRoomBranch(branch)&&!s.EnterNextRoom(),"duplicate click cannot advance");C(!run.Defeat(old,0),"old callback rejected");C(s.RoomSupplyActive==(branch==RoomBranch.Supply),"supply only in chosen supply branch");
 var positions=new Vector3[s.Enemies.Count];for(int i=0;i<positions.Length;i++)positions[i]=s.Enemies[i].transform.position;
 s.Fail();C(!s.RoomBranchChoiceOpen&&s.CanRetryRoomChain,"failed run exposes retry");int before=s.Player.CombatEpoch;int rngCalls=UnityEngine.Random.Calls,history=s.History;string receipt=s.Receipt;s.Progression.Fail=true;C(!s.RetryFailedRoomChain()&&ReferenceEquals(run,s.RoomChainRun),"failed retry save retains old state");s.Progression.Fail=false;s.SelectedDungeonTier=7;s.SelectedArenaMode=0;C(s.RetryFailedRoomChain(),"actual retry admission and reset");C(s.RoomChainRun.Room.Seed==seed&&s.RoomChainRun.SelectedBranch==branch&&s.RoomChainRun.Room.Index==0&&s.DungeonTier==originalTier&&s.ChallengeRun==originalLimited,"retry retains seed branch and conditions");C(UnityEngine.Random.Calls==rngCalls&&s.History==history&&receipt!=s.Receipt&&!string.IsNullOrEmpty(s.Receipt),"retry skips RNG and seed history rotation and creates new receipt");C(!ReferenceEquals(run,s.RoomChainRun)&&s.Player.CombatEpoch==before+1&&!s.IsDead&&!s.RetryFailedRoomChain(),"retry creates fresh state epoch and blocks duplicate");
 Complete(s);s.Tick();s.Tick();C(s.ConfirmBlessingForTest(0),"retry first blessing");Door(s);C(s.EnterNextRoom(),"retry second");Complete(s);Door(s);C(s.EnterNextRoom()&&!s.RoomBranchChoiceOpen,"retry selected branch enters directly");for(int i=0;i<positions.Length;i++)C((s.Enemies[i].transform.position-positions[i]).sqrMagnitude<.00001f,"same seed path positions");
 Complete(s);Door(s);C(s.EnterNextRoom()&&s.RoomChainRun.Room.Interlude&&s.RunChoices.CompletedWave==2,"fourth rest second blessing");C(s.ConfirmBlessingForTest(0),"second blessing admits next door");Door(s);C(s.EnterNextRoom()&&s.RoomChainRun.Room.Boss,"fifth boss convergence");Complete(s);C(s.RoomChainRun.Finished&&!s.RoomChainRun.Failed&&s.RunChoices.ActiveCountForTest()==2,"five rooms two blessings");s.Fresh();C(s.RoomChainRun!=null&&s.RoomChainRun.SelectedBranch==RoomBranch.None,"new expedition resets branch");
 }
 var exit=new GameSession(0);Complete(exit);exit.Tick();exit.Tick();exit.ConfirmBlessingForTest(0);Door(exit);exit.EnterNextRoom();Complete(exit);Door(exit);exit.EnterNextRoom();var abandoned=exit.RoomChainRun;C(exit.ExitForTest()&&exit.RoomChainRun==null&&!abandoned.BranchChoiceOpen&&!exit.CanRetryRoomChain,"exit disposes pending choice and retry context");
 var died=new GameSession(0);Complete(died);died.Tick();died.Tick();died.ConfirmBlessingForTest(0);Door(died);died.EnterNextRoom();Complete(died);Door(died);died.EnterNextRoom();died.Fail();C(!died.RoomBranchChoiceOpen&&!died.ConfirmRoomBranch(RoomBranch.Seal),"death cancels pending selection");C(died.RetryFailedRoomChain()&&died.RoomChainRun.SelectedBranch==RoomBranch.None,"retry before selection remains undecided");
 var failed=new GameSession(0);Complete(failed);failed.Tick();failed.Tick();failed.ConfirmBlessingForTest(0);Door(failed);failed.EnterNextRoom();Complete(failed);Door(failed);failed.EnterNextRoom();WorldBuilder.FailNextBuild=true;C(!failed.ConfirmRoomBranch(RoomBranch.Supply)&&failed.RoomChainRun.Failed&&!failed.Changing&&!failed.RoomBranchChoiceOpen,"world generation failure closes branch and transition gate");C(failed.RetryFailedRoomChain()&&failed.RoomChainRun.SelectedBranch==RoomBranch.Supply,"failed generation retains confirmed branch for retry");
 Console.WriteLine("PASS: "+n+" actual branch host assertions, 54 seeds x 2 paths (managed boundary doubles, not Unity)");
 }
}
namespace Emberfall{public sealed partial class GameSession{public bool ConfirmBlessingForTest(int i)=>ConfirmRoomInterlude(i);}public static class ChoiceCount{public static int ActiveCountForTest(this RunChoices r){int n=0;foreach(var b in r.Active)n++;return n;}}}
