#!/usr/bin/env python3
"""Actual loaded weapon parts + full AnimateHero/AimArm + actual ribbon sampler."""
from pathlib import Path
import subprocess,sys,os,tempfile,re
root=Path(__file__).resolve().parents[1];dotnet=sys.argv[1] if len(sys.argv)>1 else 'dotnet'
with tempfile.TemporaryDirectory(prefix='weapon-contact-') as d:
 out=Path(d).resolve();subprocess.run([sys.executable,str(root/'Tests/WeaponModulesProductionTests.py'),dotnet,str(out)],check=True);p=out/'export'
 ns={'__file__':str(root/'Tests/EquipmentCompositionProductionTests.py')};argv=sys.argv;sys.argv=['x',dotnet];exec((root/'Tests/EquipmentCompositionProductionTests.py').read_text().split('with tempfile.TemporaryDirectory')[0],ns);sys.argv=argv;extract=ns['extract'];source=(root/'Assets/Scripts/Combat/CombatModel.cs').read_text()
 for name in ['Combat/CombatModel.VanguardArt','Combat/VanguardActionLibrary','Combat/CombatModel.CastPoses','Core/HeroMotionStyle','Core/LocomotionPoseState','Core/VisualMotionEnvelope','Core/BasicActionTimeline','Core/CasterPoseRecipe']:(p/(name.split('/')[-1]+'.cs')).write_text((root/'Assets/Scripts'/(name+'.cs')).read_text())
 b=p/'OptionalPilotBoundary.cs';b.write_text(b.read_text().replace('private void ConfigureVanguardArt() {}',''))
 body='using System;using UnityEngine;namespace Emberfall {public sealed partial class CombatModel {private bool isolatedPreview,pilotOwnerDead,pilotAirborne,dying;private float previewTime,actionAge,actionDuration,gaitPhase;private int actionStartedFrame;private readonly LocomotionPoseState locomotion=new LocomotionPoseState();private readonly VisualMotionEnvelope visualMotion=new VisualMotionEnvelope();private bool SampleBlenderPilot(bool a,float b,bool c){return false;}private void AdvanceVisualMotion(float dt){throw new Exception("clock must be frozen");}private void ApplyVisualRecovery(float dt){}'
 body+=''.join(extract(source,k) for k in ['private static Quaternion Pose(','private void AnimateHero(','private static void AimArm('])+extract((root/'Assets/Scripts/Combat/CombatModel.Motion.cs').read_text(),'private void ApplyHeroLocomotion(')
 body+='''public Vector3[] ContactSample(float progress){Time.time=1;Time.frameCount=1;actionStartedFrame=1;actionDuration=1;actionAge=progress;actionBasic=true;AnimateHero(0,0,false,0);var list=new System.Collections.Generic.List<Vector3>();foreach(WeaponVisualAnchor a in Enum.GetValues(typeof(WeaponVisualAnchor))){Vector3 point;TryGetWeaponVisualAnchor(a,out point);list.Add(point);}if(bowRig!=null){var nock=bowRig.TransformPoint(bowstring.points[1]);if((nock-bowRig.TransformPoint(arrowRig.localPosition)).magnitude>.00001)throw new Exception("actual string/nock draw alignment");}if(swordRig!=null)RibbonProbe.Verify(this,list[3],list[4]);return list.ToArray();}}}
'''
 (p/'Motion.cs').write_text(body)
 ribbon=extract((root/'Assets/Scripts/Combat/WeaponVisualLinks.cs').read_text(),'private void Sample(Vector3 root,Vector3 tip)')
 (p/'Ribbon.cs').write_text('using System;using UnityEngine;namespace Emberfall{class RibbonProbe{CombatModel model;Vector3 previousRoot,previousTip;int side=1;Vector3[] vertices=new Vector3[8];Mesh mesh=new Mesh();'+ribbon+'public static void Verify(CombatModel m,Vector3 root,Vector3 tip){var p=new RibbonProbe{model=m};p.Sample(root,tip);if(((p.vertices[0]+p.vertices[4])*.5f-root).magnitude>.00001||((p.vertices[1]+p.vertices[5])*.5f-tip).magnitude>.00001)throw new Exception("real ribbon root/tip plane attachment");}}}')
 f=p/'Fixture.cs';s=f.read_text().replace('public static float deltaTime=.016f,time;','public static float deltaTime=.016f,time;public static int frameCount;')
 s=s.replace('public Quaternion rotation=>parent==null?localRotation:parent.rotation*localRotation;','public Vector3 right=>rotation*Vector3.right;public Quaternion rotation{get=>parent==null?localRotation:parent.rotation*localRotation;set=>localRotation=parent==null?value:Quaternion.Inverse(parent.rotation)*value;}public void Rotate(float x,float y,float z,Space s){localRotation=localRotation*Quaternion.Euler(x,y,z);}')
 s=s.replace('public struct Vector3 {','public enum Space{Self,World}public struct Vector3 {public static Vector3 ProjectOnPlane(Vector3 v,Vector3 n)=>v-n*(v.x*n.x+v.y*n.y+v.z*n.z);public static Vector3 Lerp(Vector3 a,Vector3 b,float t)=>a+(b-a)*Mathf.Clamp01(t);')
 s=s.replace('public struct Quaternion {','public struct Quaternion {public static Quaternion Euler(Vector3 v)=>Euler(v.x,v.y,v.z);public static Quaternion Slerp(Quaternion a,Quaternion b,float t)=>new Quaternion{q=System.Numerics.Quaternion.Slerp(a.q,b.q,t)};public static Quaternion FromToRotation(Vector3 a,Vector3 b){a=a.normalized;b=b.normalized;var v=Vector3.Cross(a,b);return new Quaternion{q=System.Numerics.Quaternion.Normalize(new System.Numerics.Quaternion(v.x,v.y,v.z,1+a.x*b.x+a.y*b.y+a.z*b.z))};}')
 s=s.replace('public static class Mathf{','public static class Mathf{public static float Sqrt(float x)=>(float)Math.Sqrt(x);public static float Max(float a,float b)=>Math.Max(a,b);public static float Min(float a,float b)=>Math.Min(a,b);public static float Pow(float a,float b)=>(float)Math.Pow(a,b);public static float SmoothStep(float a,float b,float t){t=Clamp01(t);return a+(b-a)*t*t*(3-2*t);}')
 f.write_text(s)
 (p/'Exporter.cs').write_text(r'''using System;using UnityEngine;using Emberfall;class Entry{static void Main(){int n=0;for(int h=0;h<4;h++)foreach(int tier in new[]{1,4})for(int fashion=0;fashion<2;fashion++){Vector3[][] baseline=null;for(int enabled=0;enabled<2;enabled++){WeaponModules.Enabled=enabled==1;var m=CombatModel.Hero(new GameObject("contact").transform,(HeroClass)h);m.ApplyEquipment(new ItemData{id="w",name=h==0&&tier==1?"初行长剑":"tier",slot=ItemSlot.Weapon,level=tier==1?1:76,rarity=tier==1?Rarity.Common:Rarity.Legendary,upgradeLevel=tier==1?0:10},null,null);if(fashion==1)m.ApplyFashion(null,new FashionData{id="fashion-1-3",slot=FashionSlot.Weapon,rarity=Rarity.Legendary});var phases=new[]{0f,.16f,BasicActionTimeline.Contact(h==2),.48f,.65f,.83f,1f};var now=new Vector3[phases.Length][];for(int i=0;i<phases.Length;i++){now[i]=m.ContactSample(phases[i]);if(enabled==1)for(int k=0;k<now[i].Length;k++){n++;if(float.IsNaN(now[i][k].x)||(now[i][k]-baseline[i][k]).magnitude>.0001)throw new Exception("new weapon geometry changes actual motion/contact anchor");}}if(enabled==0)baseline=now;UnityEngine.Object.Destroy(m.gameObject);UnityEngine.Object.Flush();}}Console.WriteLine("PASS "+n+" loaded 16-combination actual AnimateHero/AimArm contact anchors; real bow draw/string/nock and ribbon Sample; managed numerical transforms, not Unity");}}''')
 subprocess.run([dotnet,'run','--project',str(p/'Export.csproj')],check=True,env=dict(os.environ,DOTNET_CLI_HOME=str(out/'cli')))
